/**
 * Adventurer Cards (Return of Raria): a collection of the Realm's people, places, powers and things, each card found by
 * doing something: walking into a region, meeting someone, putting a creature down, holding an item, standing before a
 * statue, finishing a quest, keeping the Law. Nothing is given; the world is how you find them. What you've found is
 * saved with your adventure (player.cards: id → the UTC day), so a card stays found even if you later sell the thing.
 */
import { MONSTERS, isItem, type Skill } from "./data.ts";
import { ORDERS, ORDER_IDS, metOrder, type OrderId } from "./knights.ts";
import { REGIONS, WEST_DX, type RegionId } from "./world.ts";
import { FAR_PLACES, RARIA_CITY } from "./farwest.ts";
import { count, level, message, sound, type Game } from "./state.ts";
import { questDone } from "./content.ts";

export type CardKind = "order" | "leader" | "faction" | "person" | "region" | "settlement" | "enemy" | "statue" | "equipment" | "sigil" | "faith" | "magic" | "resource" | "quest" | "landmark";
export const CARD_KIND_NAMES: Record<CardKind, string> = { order: "Orders", leader: "Leaders", faction: "Factions", person: "People", region: "Regions", settlement: "Settlements", enemy: "Enemies", statue: "Statues", equipment: "Equipment", sigil: "Sigils", faith: "Faith", magic: "Magic", resource: "Resources", quest: "Quests", landmark: "Landmarks" };
export type CardUnlock = {
  /** Any of these: talking to an NPC, finishing a quest, discovering a region, a kill, owning an item, standing near a place, a quest-data flag, meeting an Order's leader (or a faction's), keeping the Law, a skill level. */
  talk?: readonly string[]; quest?: string; region?: RegionId; kill?: string; item?: readonly string[]; near?: { x: number; y: number; r: number }; flag?: string; met?: OrderId | "fff" | "raria" | "watcher"; rarian?: boolean; skill?: [Skill, number];
};
export type CardDef = {
  id: string; name: string; kind: CardKind; text: string; hint: string; unlock: CardUnlock;
  /** What the card shows: an item's icon, a person's sprite, a creature's, a statue's art, or a colour. */
  art: { item?: string; npc?: string; monster?: string; decor?: string; color?: string };
  /** An Order's card (its leader must be met before any of its cards can be found), or a faction's. */
  order?: OrderId; faction?: "fff" | "raria" | "hollowmere";
};
/** A spot in the legacy frame (everything west-built before the far west), moved into world coordinates. */
const L = (x: number, y: number, r: number) => ({ x: x + WEST_DX, y, r });
const F = (at: readonly [number, number], r: number) => ({ x: at[0], y: at[1], r });
const card = (id: string, name: string, kind: CardKind, text: string, hint: string, unlock: CardUnlock, art: CardDef["art"], extra: Partial<Pick<CardDef, "order" | "faction">> = {}): CardDef => ({ id, name, kind, text, hint, unlock, art, ...extra });
const REGION_TEXT: Partial<Record<RegionId, string>> = {
  deep_westmarch: "The border nobody drew: Hollowmere's last post, the Regiment's checkpoint, the Federation's pickets, and the Stone Field between them, where the watch-stones fell westward.",
  free_marches: "The Federation's wet green south-west of Westmarch, pines and outcrops and a palisade of stakes no two the same height.",
  barkreach: "The great wood of the far west's south: thousands of redwoods, ironbarks, oaks and maples, greatstags, and the camps and village of people who cut, hunt and watch.",
  raria: "The kingdom that was not there in spring: a second continent's worth of it, the walled capital round its palace in the middle, every street swept, every corner watched.",
  raria_march: "Raria's eastern march by the Drakespine: Lawgate's walls, the Spine Watch, and the Crown Road running west into the kingdom.",
  crownlands: "Raria's farms between the capital and the march: Candlemere on its lake, a windmill turning to the regulation, and the tithe always due.",
  vesperwold: "The dark hills north of the capital: Vesperholm Abbey under its bell, dusk wraiths in the wood after the last bell, and the Royal Rangers' Hold.",
  silent_peaks: "Snow and scree in the far north-west, moonsilver and rarite in the rock, stone watchers that move when nobody looks, and the Blind Shrine.",
  heartwood: "The oldest end of BarkReach, ironbark and yew so thick the light comes in green, a glade nobody planted, and the Ironbark Elder.",
  greyfields: "The war between Raria and the Federation: Fort Ordinance, the Federation's forward camp, and the battlefield between where the dead haven't stopped.",
  westmarch: "Rolling downs with dark heather, the West Road through them, a burned farmhouse nobody explains, and the watch-stones, toppled westward.",
  drakespine: "The peninsula of cliff and scree between Westmarch and Ashfall, where the drakes circle and the Regiment's Spine Watch looks north.",
  ashfall: "Ash fields, lava and the Order of the Ember's fortress on its island in the moat, with the Burned walking the ash round it.",
  deadwood: "The wood where it is always night: the dead trees, the black river, Gravesend's lanterns, the Maidens' camp, the great ruined chapel.",
  friendhollow: "The Kingdom of Hollowmere's heart: the square, the castle built against something from the west, and the Namekeeper's register.",
};
export const CARDS: readonly CardDef[] = [
  // ---------- Regions: walk in ----------
  ...REGIONS.filter(region => region.id !== "coast").map(region => card(`region_${region.id}`, region.name, "region", REGION_TEXT[region.id] ?? `${region.name}: danger ${region.danger}. You have walked here.`, "Discover it on foot.", { region: region.id }, { color: region.underground ? "#2f2d2b" : region.danger >= 4 ? "#5a2a24" : region.danger >= 2 ? "#4a3a5c" : "#4f7a4a" })),
  // ---------- Settlements and landmarks: stand there ----------
  card("place_raria_palace", "The Palace of Raria", "landmark", "In the exact centre of the city, three storeys and a tower's height, the throne room on the ground floor with the Wise Friend in ivory beside the throne. The whole city circles it.", "Stand before the throne of Raria.", { near: { x: RARIA_CITY.x, y: RARIA_CITY.y - 8, r: 7 } }, { decor: "throne" }, { faction: "raria" }),
  card("place_fff_fortress", "The FFF Fortress", "landmark", "Fortress, wizard academy, workshop, laboratory, armoury, ranger post and library at once, inside a palisade of stakes. The architecture is eccentric. So is everyone in it.", "Stand in the Federation's Great Hall.", { near: L(40, 397, 7) }, { decor: "cannon" }, { faction: "fff" }),
  card("place_sawyers_rest", "Sawyer's Rest", "settlement", "BarkReach's logging camp on the wood road: the Heartwood Yard, the Antler and Bow, Resin and Hide, and a stump as wide as a table, used as one.", "Visit the logging camp in BarkReach.", { near: F(FAR_PLACES.sawyers_rest, 9) }, { decor: "logpile" }),
  card("place_antler_lodge", "The Antler Lodge", "settlement", "The rangers' settlement up the wood, with the bowyers' targets and a tally of every greatstag carved in antler.", "Visit the rangers' lodge in BarkReach.", { near: F(FAR_PLACES.antler_lodge, 7) }, { decor: "target" }),
  card("place_stags_rest", "The Stag's Rest", "settlement", "The hunters' camp toward the vale: tents, hides drying, a greatstag haunch over the fire, always.", "Visit the hunting camp in BarkReach.", { near: F(FAR_PLACES.stags_rest, 7) }, { decor: "tent" }),
  card("place_freehold", "Freehold", "settlement", "Nobody's village, outside the Federation's gate: a free bank, a free fire, and a device on somebody's roof that sings at night.", "Visit Freehold in the Free Marches.", { near: L(70, 412, 9) }, { decor: "device" }, { faction: "fff" }),
  card("place_westwatch", "Westwatch", "settlement", "The Kingdom of Hollowmere's last post, north of the West Road, where the word Raria was first said out loud.", "Visit Westwatch in Deep Westmarch.", { near: L(92, 282, 9) }, { decor: "banner_hollowmere" }, { faction: "hollowmere" }),
  card("place_checkpoint", "The Regiment's checkpoint", "landmark", "Stakes across the West Road, two halberdiers, a captain who writes writs and writes down who asks for them. The Wise Friend sees.", "Reach the Regiment's checkpoint on the West Road.", { near: L(30, 285, 8) }, { decor: "stake" }, { faction: "raria" }),
  card("place_stone_field", "The Stone Field", "landmark", "Where the first fighting was. Hollowmere's dead and Raria's in the same ground, a broken halberd in the turf, and the old watch-stones, toppled westward.", "Walk the Stone Field in Deep Westmarch.", { near: L(62, 290, 9) }, { decor: "bones" }),
  card("place_old_westwatch", "Old Westwatch", "landmark", "The tower the kingdom built out here long ago and forgot. A pillar in it carries Hollowmere's crown and, under it, older, the symbol from the stones.", "Find the ruined tower in Deep Westmarch.", { near: L(18, 334, 7) }, { decor: "ruin_wall" }),
  card("place_hidden_hollow", "The Hollow of the Stones", "landmark", "A ring of cliff west of the checkpoint with one way in, a statue of the Wise Friend in it with moss to the blindfold, and flowers at its feet every day. Older than any kingdom west of the Spine.", "Find the hidden hollow in Deep Westmarch.", { near: L(12, 302, 6) }, { decor: "wise_friend" }),
  card("place_wood_glade", "The Glade in the Wood", "landmark", "Cliffs all round, one way in, and a statue of the Wise Friend sunk to the chest in the loam among the oldest ironbarks. Raria did not put it there.", "Find the hidden glade in BarkReach.", { near: F(FAR_PLACES.hidden_glade, 6) }, { decor: "wise_friend" }),
  card("place_spine_watch", "The Spine Watch", "landmark", "The Regiment's northern camp, where it looks at the Drakespine and the Drakespine looks back. It had a tower.", "Reach the Spine Watch north of Raria.", { near: L(38, 168, 10) }, { decor: "watchtower" }, { faction: "raria" }),
  card("place_dusk_cemetery", "The Dusk's cemetery", "landmark", "Every grave the same, every name in the Ledger, counted at dusk. The count has never been wrong.", "Walk the cemetery north of Raria's wall.", { near: { x: RARIA_CITY.x0 + 21, y: RARIA_CITY.y0 - 9, r: 10 } }, { decor: "grave" }, { faction: "raria" }),
  card("place_ember_fortress", "The Ember Fortress", "landmark", "The Order of the Ember's fortress on its island of ash inside a moat of lava, a causeway of blackened stone to its gate, and the Burned in the ash round it.", "Stand before the Ember Fortress at Ashfall.", { near: L(72, 100, 16) }, { decor: "god_ember" }, { order: "ember" }),
  card("place_the_ring", "The Rare Friends Ring", "landmark", "The round building west of the Deadwood, built by a Hoverer so the best fighters in the land could meet, where the stones stand the fallen back up.", "Visit the Rare Friends Ring.", { region: "friends_ring" }, { color: "#5a1f2e" }),
  ...ORDER_IDS.filter(id => id !== "ember" && id !== "dusk").map(id => card(`place_${id}_hall`, `The ${ORDERS[id].short} Hall`, "landmark", `The ${ORDERS[id].name}'s hall: stone under a roof in the Order's colour, the altar at the north end, the god's statue before the door between two banners and two knights.`, `Visit the ${ORDERS[id].short} Hall.`, { near: L(ORDERS[id].near[0], ORDERS[id].near[1], 26) }, { decor: ORDERS[id].statue }, { order: id })),
  card("place_dusk_hall", "The Hall of the Order of Dusk", "landmark", "A dark hall south of Raria's palace, the Wise Friend hooded over its altar, crooks and censer-maces racked by touch.", "Visit the Hall of the Order of Dusk in Raria.", { near: { x: ORDERS.dusk.near[0], y: ORDERS.dusk.near[1] + 4, r: 7 } }, { decor: "god_dusk" }, { order: "dusk" }),
  card("place_lawgate", "Lawgate", "settlement", "Raria's fortress town on its eastern march, facing the Drakespine: the Governor's Hall, a chapel, a garrison, an inn called the Obedient Hound, and the Crown Road running west.", "Visit Lawgate.", { near: L(26, 214, 12) }, { decor: "banner_rrr" }, { faction: "raria" }),
  card("place_vesperholm", "Vesperholm Abbey", "settlement", "The Order of Dusk's abbey town in the Vesperwold, under its bell tower, among its graves. The last bell of the day for all Raria rings here.", "Visit Vesperholm.", { near: F(FAR_PLACES.vesperholm, 12) }, { decor: "god_dusk" }, { order: "dusk" }),
  card("place_rangers_hold", "The Rangers' Hold", "landmark", "The Royal Rangers' lodge in the Vesperwold. Property of the Crown. You have already been seen.", "Find the Rangers' Hold.", { near: F(FAR_PLACES.rangers_hold, 9) }, { monster: "royal_ranger" }, { faction: "raria" }),
  card("place_candlemere", "Candlemere", "settlement", "The Crownlands' lake town: farms, a windmill turning to the regulation, fishing with thanks, and a reeve who answers for the tithe.", "Visit Candlemere.", { near: F(FAR_PLACES.candlemere, 12) }, { decor: "windmill" }, { faction: "raria" }),
  card("place_greyford", "Greyford", "settlement", "The river town where the South Road crosses the Vesper, the last of the Crown before the Greyfields.", "Visit Greyford.", { near: F(FAR_PLACES.greyford, 10) }, { decor: "banner_rrr" }, { faction: "raria" }),
  card("place_fort_ordinance", "Fort Ordinance", "landmark", "The Regiment's fortress in the Greyfields: a keep, towers, a war table with the Federation's camp marked in red.", "Reach Fort Ordinance.", { near: F(FAR_PLACES.fort_ordinance, 14) }, { decor: "watchtower" }, { faction: "raria" }),
  card("place_freecamp", "Freecamp", "landmark", "The Federation's forward camp in the Greyfields, with a small cannon the artisans call 'Second Opinion' pointed at Fort Ordinance.", "Find the Federation's forward camp.", { near: F(FAR_PLACES.freecamp, 10) }, { decor: "cannon" }, { faction: "fff" }),
  card("place_greyfields_battlefield", "The Greyfields battlefield", "landmark", "Bones, broken halberds, craters where the Federation's shot landed, and a cairn with FFF scratched on one side and RRR on the other.", "Walk the battlefield in the Greyfields.", { near: F(FAR_PLACES.battlefield, 16) }, { decor: "bones" }),
  card("place_woods_end", "Wood's End", "settlement", "The trading post at BarkReach's eastern edge, where the Federation's road comes in.", "Visit Wood's End.", { near: F(FAR_PLACES.woods_end, 8) }, { decor: "crate" }),
  card("place_barkholm", "Barkholm", "settlement", "The wood's own village by the Hush. The Crown asked for a tithe twice. The wood answered both times.", "Visit Barkholm.", { near: F(FAR_PLACES.barkholm, 10) }, { decor: "logpile" }),
  card("place_blind_shrine", "The Blind Shrine", "landmark", "The Wise Friend carved out of the mountain itself in the Silent Peaks, blindfolded. Under the blindfold, if you look closely, the eyes are carved open.", "Find the shrine in the Silent Peaks.", { near: F(FAR_PLACES.blind_shrine, 7) }, { decor: "wise_friend" }),
  card("place_raria_city", "The City of Raria", "settlement", "Walls and towers round a hundred streets, every one swept: the palace in the exact centre, the Chapel of the Law, the offices, the market, the barracks, the houses where everyone owns one book.", "Enter the capital.", { near: { x: RARIA_CITY.x, y: RARIA_CITY.y, r: 58 } }, { decor: "banner_rrr" }, { faction: "raria" }),
  card("person_governor", "Governor Ancel Marrowby", "person", "Governor of Lawgate. Keeps the oldest roll of the march in a drawer: Lawgate on it, and a blank where Hollowmere should be.", "Speak with the Governor of Lawgate.", { talk: ["lawgate_governor"] }, { npc: "lawgate_governor" }, { faction: "raria" }),
  card("person_abbess", "Abbess Ilse Nocturne", "person", "Abbess of Vesperholm, the Order of Dusk's eldest. Rings the last bell herself.", "Speak with the Abbess of Vesperholm.", { talk: ["vesper_abbess"] }, { npc: "vesper_abbess" }, { order: "dusk" }),
  card("person_ranger_warden", "Ranger-Warden Sable", "person", "A Royal Ranger permitted to speak, which she does as little as possible.", "Speak with the Ranger-Warden.", { talk: ["ranger_warden"] }, { npc: "ranger_warden" }, { faction: "raria" }),
  card("person_blind_hermit", "The Blind Hermit", "person", "Blindfolded like the statue, at the Blind Shrine, asking who closed the Wise Friend's eyes, and when, and what they were looking at.", "Find the hermit in the Silent Peaks.", { talk: ["peak_hermit"] }, { npc: "peak_hermit" }),
  // ---------- Factions ----------
  card("faction_hollowmere", "The Kingdom of Hollowmere", "faction", "Friendhollow's kingdom, named: King Hollis's crown, the crimson and gold, the garrison by the square, Westwatch at the end of its road. It built its castle against something from the west, and has forgotten what.", "Speak with Captain Ashby of the Hollowmere garrison.", { talk: ["hollowmere_officer"] }, { decor: "banner_hollowmere" }, { faction: "hollowmere" }),
  card("faction_fff", "The Free Friends Federation", "faction", "FFF. Wizards, knights, rangers and artisans who answer to nobody and built a fortress, a cannon and a bank with no fees to prove it. Weird, serious, whimsical, radical, and extremely competent. They mostly keep to themselves.", "Be known to the Federation.", { quest: "fff_truce" }, { item: "fff_cape_elite" }, { faction: "fff" }),
  card("faction_raria", "The Kingdom of Raria", "faction", "Order. Law. Faith. Hierarchy. Discipline. Authority. The Wise Friend, the Crown, the Regiment and the Order of Dusk, in a city that was not there before. Everything is beautiful, and everyone is polite, and something is wrong.", "Be registered in Raria's Ledger.", { quest: "rrr_truce" }, { item: "rarian_mantle" }, { faction: "raria" }),
  card("faction_rrr", "The Rare Realm Regiment", "faction", "RRR. Raria's army: professional, organised, heavily armed, trained to the inch, and ready for a war it is already fighting in Deep Westmarch. Every soldier the same. Every shield the same.", "Put down a soldier of the Regiment, or carry its writ.", { kill: "rrr_footman", item: ["writ_of_passage", "rrr_banner"] }, { item: "rrr_heater" }, { faction: "raria" }),
  card("faction_royal_rangers", "The Raria Royal Rangers", "faction", "The royal family's own guard, everywhere in the city and never where you expect: behind a pillar, in the garden, at the chapel door, on the wall. Extremely high level. They are not looking at you. They have already looked.", "See a Royal Ranger up close.", { near: { x: RARIA_CITY.x, y: RARIA_CITY.y, r: 60 }, kill: "royal_ranger" }, { monster: "royal_ranger" }, { faction: "raria" }),
  card("faction_maidens", "The Deadwood Maidens", "faction", "The spearwomen of the east Deadwood, who hold it against the dead and against everyone else until a truce is kept.", "Keep the Maidens' truce.", { quest: "maidens_truce" }, { item: "maiden_veil" }),
  card("faction_dawn", "The Order of the Dawn", "faction", "The knights of Dawnhold, white and gold, who keep the vigil, walk the Pilgrim's Road and carry the Vigil Aegis.", "Keep the Dawn Vigil.", { quest: "dawn_vigil" }, { item: "vigil_shield" }),
  // ---------- Orders and their gods (met the leader first) ----------
  ...ORDER_IDS.map(id => card(`order_${id}`, ORDERS[id].name, "order", `${ORDERS[id].godText} ${ORDERS[id].effect}`, `Meet ${ORDERS[id].leaderName}.`, { met: id }, { decor: ORDERS[id].statue }, { order: id })),
  ...ORDER_IDS.map(id => card(`leader_${id}`, ORDERS[id].leaderName, "leader", id === "dusk" ? "Prior of the Order of Dusk. Speaks quietly, moves quietly, has not been seen to blink, and keeps what the Law forbids anyone to see from being seen." : `Commander of the ${ORDERS[id].name}, who swears in those who prove their faith: ${ORDERS[id].oath.text}.`, `Talk to ${ORDERS[id].leaderName}.`, { met: id }, { npc: ORDERS[id].leader }, { order: id })),
  ...ORDER_IDS.map(id => card(`statue_${id}`, `${ORDERS[id].god}, carved`, "statue", id === "ember" ? "A great iron brazier on a plinth and the Ember's flame rising out of it: the Order serves no god but the fire it keeps burning." : id === "dusk" ? "The Wise Friend as the Dusk carves it: seated, hooded, blindfolded, the book open, a censer at its feet." : `${ORDERS[id].god}, carved and painted in the Order's colours on a stepped plinth with the colour inlaid along its face.`, `Stand before the ${ORDERS[id].short}'s statue, having met its leader.`, { met: id, near: id === "dusk" ? { x: ORDERS.dusk.near[0], y: ORDERS.dusk.near[1] - 1, r: 4 } : L(ORDERS[id].near[0], ORDERS[id].near[1], 26) }, { decor: ORDERS[id].statue }, { order: id })),
  ...ORDER_IDS.map(id => card(`gear_${id}`, `${ORDERS[id].short} ${ORDERS[id].tiers?.paladin ?? "Paladin"} plate`, "equipment", `The ${ORDERS[id].name}'s armour in three tiers, blessed at its altar, every piece carrying its blessing: ${ORDERS[id].each}.`, `Own a piece of the ${ORDERS[id].short}'s gear.`, { met: id, item: [`${id}_oath_helm`, `${id}_oath_body`, `${id}_knight_body`, `${id}_paladin_body`, `${id}_oath_kite`, `${id}_oath_mace`, `${id}_cape`] }, { item: `${id}_paladin_body` }, { order: id })),
  // ---------- Leaders and people ----------
  card("person_queen_rara", "Her Radiance, Queen Rara", "leader", "Queen of Raria, Keeper of the Wise Friend's Law. Tall, still, beautiful, certain. Not cruel: certain. She believes the Law completely, and that is what makes her dangerous.", "Be received by the Queen.", { talk: ["queen_rara"] }, { npc: "queen_rara" }, { faction: "raria" }),
  card("person_king_pell", "King Pell", "leader", "The Queen's husband: scrawny, kind, nervous, with ink on his fingers. Physically tiny beside her. Sees everything in the room and says very little about it. He has read the Law twice.", "Speak with the King.", { talk: ["king_pell"] }, { npc: "king_pell" }, { faction: "raria" }),
  card("person_fellow_free", "Fellow Free, First Free of the Federation", "leader", "Fourteen devices running, three swords from the ceiling, a half-built cannon, a knight asleep, a chicken in a cape, and him in the middle of it, completely serious. Weird. Brilliant. Dangerous.", "Meet Fellow Free in the Great Hall.", { met: "fff" }, { npc: "fellow_free" }, { faction: "fff" }),
  card("person_captain_ashby", "Captain Wren Ashby", "person", "Captain of the Hollowmere garrison, with a map of the west with a hole in it where Raria is.", "Speak with the captain by the Friendhollow square.", { talk: ["hollowmere_officer"] }, { npc: "hollowmere_officer" }, { faction: "hollowmere" }),
  card("person_gate_warden", "Gate-Warden Pip Quarrel", "person", "The Federation's only bureaucrat. Apologises for it. Asks three questions of everyone and means them; the right answers are the honest ones.", "Answer the Gate Question.", { talk: ["fff_gatewarden"] }, { npc: "fff_gatewarden" }, { faction: "fff" }),
  card("person_archwizard", "Archwizard Mab Ferrule", "person", "Runs the Wizard Tower. Has blown it up twice and rebuilt it taller both times. Her spellbook's corrections are in red.", "Speak with the Archwizard.", { talk: ["fff_archwizard"] }, { npc: "fff_archwizard" }, { faction: "fff" }),
  card("person_captain_vane", "Captain Aurelle Vane", "person", "Commands the Regiment's checkpoint on the West Road. Writes writs. Writes down who asks.", "Speak with the captain at the checkpoint.", { talk: ["raria_gate_captain"] }, { npc: "raria_gate_captain" }, { faction: "raria" }),
  card("person_colonel_marsh", "Colonel Severin Marsh", "person", "Colonel of the Rare Realm Regiment, in the barracks, with a map of the west on which Raria is most of it.", "Speak with the Colonel in Raria.", { talk: ["rrr_officer"] }, { npc: "rrr_officer" }, { faction: "raria" }),
  card("person_assessor", "Assessor Linnet Marrow", "person", "Assessor of the Ledger of Names. Knows what every citizen bought, prayed and said last week, and would like to know this week's. It is only paperwork.", "Speak with the Assessor.", { talk: ["raria_assessor"] }, { npc: "raria_assessor" }, { faction: "raria" }),
  card("person_watcher", "The Watcher of the Stones", "person", "An old Friend who keeps a statue nobody else knows is there, with flowers in one hand and a candle in the other. Nobody's Ledger has them.", "Find the Watcher.", { met: "watcher" }, { npc: "west_watcher" }),
  card("person_tam_merrow", "The Unwritten Name", "person", "A citizen who prayed four times instead of seven, because his daughter was ill and the chapel is across the city. You said you found nothing. His mother's crown sigils aren't in any ledger either.", "Spare a citizen of Raria.", { flag: "card_unwritten" }, { npc: "raria_citizen_merrow" }, { faction: "raria" }),
  card("person_sir_haddock", "Sir Haddock, asleep", "person", "A knight of the Federation, asleep in a chair in the Great Hall in full plate, since the cannon's first test. He is fine. He is the only one who is.", "Wake Sir Haddock.", { flag: "ft_knight" }, { npc: "fff_knight_asleep" }, { faction: "fff" }),
  card("person_admiral_peck", "Admiral Peck", "person", "A chicken in an FFF cape. Rank: admiral. Outranks Sir Haddock. Nobody at the fortress will explain this, and nobody is joking.", "Meet the admiral.", { near: L(43, 399, 5), kill: "admiral_peck" }, { monster: "admiral_peck" }, { faction: "fff" }),
  card("person_ringmaster", "Ringmaster Vell Harrow", "person", "Runs the Rare Friends Ring. Has seen every match since the Ringmaker's day, or says so.", "Talk to the Ringmaster.", { talk: ["ringmaster"] }, { npc: "ringmaster" }),
  card("person_matriarch", "Matriarch Ysolde Thornveil", "person", "Leads the Deadwood Maidens. Has buried more of the dead than Gravesend has.", "Talk to the Matriarch.", { talk: ["maiden_matriarch"] }, { npc: "maiden_matriarch" }),
  card("person_king_hollis", "King Hollis", "person", "King of Hollowmere, who has never been seen to leave his castle. Not once. Not even for the Feast.", "Talk to the King in Friendhollow Castle.", { talk: ["king"] }, { npc: "king" }, { faction: "hollowmere" }),
  // ---------- Enemies ----------
  ...(["rrr_scout", "rrr_archer", "rrr_footman", "rrr_halberdier", "rrr_captain", "fff_picket", "fff_warden", "greatstag", "bark_lurker", "timber_thief", "deserter", "royal_ranger", "crown_hound", "dusk_wraith", "greyfield_revenant", "ironbark_treant", "peak_watcher", "deadwood_maiden", "stone_knight", "revenant_king", "howling_king", "crystal_golem", "archivist_below", "rat_king", "moss_warden", "ash_drake", "hollow_king"] as const).filter(id => MONSTERS[id]).map(id =>
    card(`enemy_${id}`, MONSTERS[id].name, "enemy", MONSTERS[id].examine, `Put one down (level ${MONSTERS[id].level}).`, { kill: id }, { monster: id }, id.startsWith("rrr_") || id === "royal_ranger" ? { faction: "raria" } : id.startsWith("fff_") ? { faction: "fff" } : {})),
  card("enemy_the_burned", "The Burned", "enemy", "The dead of the villages Ashfall took, walking the ash round the Ember Fortress in the red of old embers: every build of Friend the Realm's villages have, and one of the Order's own. They carry what they carried. Water quenches them.", "Put down one of the Burned at Ashfall.", { kill: "burned_average", flag: "card_burned" }, { monster: "burned_average" }, { order: "ember" }),
  card("enemy_burned_pair", "The Burned, hand in hand", "enemy", "Two of the Burned, a tall one and a small one, hand in hand. They do not let go, even now. The hardest of them to fight, for the wrong reasons.", "Put down the Burned pair.", { kill: "burned_parent" }, { monster: "burned_parent" }, { order: "ember" }),
  card("enemy_burned_knight", "The Burned knight", "enemy", "One of the Order of the Ember's own, burnt in its plate, faded red through the joints. It kept its sword. The Order keeps its name.", "Put down the Burned knight.", { kill: "burned_knight" }, { monster: "burned_knight" }, { order: "ember" }),
  // ---------- Equipment: hold it ----------
  card("item_vigil_aegis", "The Vigil Aegis", "equipment", "The Order of the Dawn's tall pale-steel shield with the sun blazed across it, carried by those who keep the watch. One pattern; every one blessed at the Dawnhold altar by name.", "Hold the Vigil Aegis.", { item: ["vigil_shield"] }, { item: "vigil_shield" }),
  card("item_fff_capes", "The Federation's capes", "equipment", "Six cuts, one word: FFF in brass across the back. Wizard, knight, ranger, artisan, ceremonial, and the elite's black, which Fellow Free gives by hand.", "Wear a Federation cape.", { item: ["fff_cape_wizard", "fff_cape_knight", "fff_cape_ranger", "fff_cape_artisan", "fff_cape_elite", "fff_cape_ceremonial", "fff_cape_magical"] }, { item: "fff_cape_knight" }, { faction: "fff" }),
  card("item_fff_cannon", "Solution", "equipment", "The Federation's magical cannon, finished, on its carriage, pointed north. The artisans named it. It fired once, and the Spine Watch has no tower.", "Fire the cannon.", { quest: "fff_cannon" }, { decor: "cannon" }, { faction: "fff" }),
  card("item_fff_arms", "Federation steel", "equipment", "Copper-washed steel and verdigris: sword, greatsword, glaive, mace, the tower shield with FFF a hand high, and plate that dries.", "Own a Federation weapon or piece of plate.", { item: ["fff_sword", "fff_greatsword", "fff_glaive", "fff_mace", "fff_tower_shield", "fff_heater", "fff_cuirass", "fff_helm"] }, { item: "fff_cuirass" }, { faction: "fff" }),
  card("item_fff_ranged", "The Rangers' Yard", "equipment", "The longbow of three woods and a copper strip; the repeater that only jams on Tuesdays; the rangers' leathers; broadheads that go through things.", "Own a Federation bow or ranger's piece.", { item: ["fff_longbow", "fff_repeater", "fff_ranger_hood", "fff_ranger_jerkin", "fff_ranger_chaps", "fff_arcane_bow"] }, { item: "fff_longbow" }, { faction: "fff" }),
  card("item_fff_magic", "The Wizard Tower's robes", "equipment", "Reinforced, because Federation wizards stand in the front line out of principle: robes, coats, hats, hoods, the spellward, the spellbook you hold like a shield, staffs, wands, the device pack.", "Own a piece of the Tower's magic gear.", { item: ["fff_wizard_robe", "fff_reinforced_robe", "fff_battle_robe", "fff_mage_coat", "fff_staff", "fff_wand", "fff_spellbook", "fff_spellward", "fff_arcane_shield", "fff_device_pack", "fff_warcaster_plate"] }, { item: "fff_staff" }, { faction: "fff" }),
  card("item_rrr_plate", "Regiment plate", "equipment", "Grey steel, violet enamel, the Wise Friend's closed eye on the breast. Inspected weekly. Every piece the same as the last; that is the point.", "Own a piece of Regiment plate.", { item: ["rrr_helm", "rrr_cuirass", "rrr_greaves", "rrr_gauntlets", "rrr_boots", "rrr_heater"] }, { item: "rrr_cuirass" }, { faction: "raria" }),
  card("item_rarian_steel", "Rarian steel", "equipment", "Blessed in the palace chapel before issue: the sword with a line of the Law down the fuller, the greatsword, spear, halberd, dagger, mace, crossbow, bow, and the staff of the Law.", "Own a Rarian weapon.", { item: ["rarian_sword", "rarian_greatsword", "rarian_spear", "rarian_halberd", "rarian_dagger", "rarian_mace", "rarian_crossbow", "rarian_bow", "rarian_staff"] }, { item: "rarian_greatsword" }, { faction: "raria" }),
  card("item_royal_rangers_gear", "The Royal Rangers' leathers", "equipment", "Not sold anywhere. Violet coat over silver mail, the hood worn low, soles for rooftops, and the dusk-black longbow that reaches nine tiles.", "Take a Royal Ranger's gear.", { item: ["ranger_royal_hood", "ranger_royal_coat", "ranger_royal_leggings", "rangers_longbow"] }, { item: "rangers_longbow" }, { faction: "raria" }),
  card("item_wise_vestments", "The Wise Friend's vestments", "equipment", "Ivory with a violet band: cowl, vestment, skirts, sandals, and the tall pavise with the first line of the Law beneath the eye: OBEY, AND BE WISE.", "Own a piece of the Wise Friend's vestments.", { item: ["wise_cowl", "wise_vestment", "wise_skirts", "wise_sandals", "wise_pavise"] }, { item: "wise_pavise" }, { faction: "raria" }),
  card("item_rarian_shields", "Raria's shields", "equipment", "The Regiment's heater with the closed eye, the Wise Friend's pavise, the Crown's ivory kite given and never sold, and the Dusk's pavise and aegis.", "Own a Rarian shield.", { item: ["rrr_heater", "wise_pavise", "royal_kite", "dusk_oath_kite", "dusk_oath_aegis", "dusk_knight_kite", "dusk_paladin_aegis"] }, { item: "royal_kite" }, { faction: "raria" }),
  card("item_back_items", "What Raria wears on its back", "equipment", "Banners, books and scroll cases instead of capes: the Regiment's banner, the faith banner, the ritual scroll case, the sigil frame, the ceremonial standard, the Book of the Law.", "Wear a Rarian back item.", { item: ["rrr_banner", "faith_banner", "ritual_scroll_case", "sigil_frame", "ceremonial_standard", "law_book"] }, { item: "faith_banner" }, { faction: "raria" }),
  card("item_rarian_clothes", "The Sumptuary Office's violet", "equipment", "Veil, tabard, skirts, slippers and mantle, in the one colour the Law allows. Other colours are confiscated at the gate.", "Own a piece of Rarian clothing.", { item: ["rarian_veil", "rarian_tabard", "rarian_skirts", "rarian_slippers", "rarian_mantle"] }, { item: "rarian_tabard" }, { faction: "raria" }),
  card("item_hollowmere_cape", "The Hollowmere cape", "equipment", "The crown's crimson, the crown in gold on the back: the Western Watch's thanks for a report nobody at the castle wanted.", "Earn the Hollowmere cape.", { item: ["hollowmere_cape"] }, { item: "hollowmere_cape" }, { faction: "hollowmere" }),
  card("item_dusk_lantern", "The Dusk lantern", "equipment", "Violet glass at the belt: its light is dim and does not flicker, and the dead keep further from it than from a torch.", "Earn the Dusk's lantern.", { item: ["dusk_lantern"] }, { item: "dusk_lantern" }, { order: "dusk" }),
  card("item_barkreach_bows", "BarkReach bows", "equipment", "Redwood and ironbark, plain and war, antler-nocked; and the woodsman's bow the Heartwood Yard pays in.", "Own a BarkReach bow.", { item: ["redwood_bow", "ironbark_bow", "redwood_war_bow", "ironbark_war_bow", "woodsmans_bow"] }, { item: "ironbark_bow" }),
  card("item_ringmasters_signet", "The Ringmaster's signet", "equipment", "A ring that carries you to the Rare Friends Ring three times a day and lends the hand that wears it the pit's strength.", "Earn the Ringmaster's signet.", { item: ["ringmasters_signet"] }, { item: "ringmasters_signet" }),
  // ---------- Sigils, faith and magic ----------
  card("sigil_law", "Law sigils", "sigil", "Pressed at the Law altar in Raria's Office of Sigils: grey-violet, stamped with the closed eye. The edicts and vigils of the Law are cast with them.", "Hold a law sigil.", { item: ["law_sigil"] }, { item: "law_sigil" }, { faction: "raria" }),
  card("sigil_dusk", "Dusk sigils", "sigil", "Pressed at the Dusk altar in the Order's hall, in the last hour of the day (any hour will do; the Prior does not check). The rites and the Edict of Dusk take them.", "Hold a dusk sigil.", { item: ["dusk_sigil"] }, { item: "dusk_sigil" }, { order: "dusk" }),
  card("sigil_crown", "Crown sigils", "sigil", "Pressed at the Crown altar under seal, gold, and counted; especially the sigils.", "Hold a crown sigil.", { item: ["crown_sigil"] }, { item: "crown_sigil" }, { faction: "raria" }),
  card("faith_wise_friend", "The Wise Friend", "faith", "Raria's faith: a Rare Friend of legend carved seated and blindfolded, a book open on its knees, who gave the Law and closed its eyes so as never to see it broken. Wisdom, Law, discipline, order, obedience, responsibility, correct conduct.", "Pray at the Wise Friend's altar.", { flag: "wfl_prayed" }, { decor: "wise_friend" }, { faction: "raria" }),
  card("faith_the_law", "The Wise Friend's Law", "faith", "Kept in place of the Old Friend's prayers: the First Law (obey), the Second (endure), the Third (strike true), the Fourth (know), the Queen's Peace, the Keeper's Silence, the Wise Hand and the Mantle of Dusk.", "Keep the Law.", { rarian: true }, { item: "law_book" }, { faction: "raria" }),
  card("faith_old_friend", "The Old Friend", "faith", "The one every altar in the Realm is raised to: a bearded Rare Friend carved in pale stone on a stepped plinth, a sun disc behind its head. Raria says it is the Wise Friend with its eyes open, which is worse.", "Speak with Brother Ossic in the Friendhollow chapel, or walk the Pilgrim's Road.", { talk: ["priest"], flag: "pilgrim_chapel" }, { decor: "old_friend" }),
  card("magic_edicts", "Edicts of the Law", "magic", "Raria's combat magic: the Edict of Silence, the Edict of Ash, the Edict of Dusk. A rite with a staff in it: structured, formal, pronounced.", "Keep the Law with Magic 20.", { rarian: true, skill: ["magic", 20] }, { item: "rarian_staff" }, { faction: "raria" }),
  card("magic_rites", "Rites of the Wise Friend", "magic", "Raria's faith magic in place of the Old Friend's light: Censure, Mending, the Keeper's rite, Obedience, and the last rite of the Order of Dusk.", "Keep the Law with Faith 20.", { rarian: true, skill: ["prayer", 20] }, { item: "ritual_scroll_case" }, { faction: "raria" }),
  card("magic_federation", "Federation magic", "magic", "Experimental, inventive, improvised, arcane, artisan-oriented: an argument with a crystal in it. Louder than Raria's, and the Tower has the scorch marks to prove it.", "Own a Federation staff, wand or spellbook.", { item: ["fff_staff", "fff_wand", "fff_spellbook"] }, { item: "fff_wand" }, { faction: "fff" }),
  // ---------- Resources ----------
  card("resource_redwood", "Redwood", "resource", "Red-hearted logs from BarkReach's tall redwoods (Woodcutting 52). They smell of resin and rain and fletch into the hunters' bows.", "Cut or hold redwood logs.", { item: ["redwood_logs"] }, { item: "redwood_logs" }),
  card("resource_ironbark", "Ironbark", "resource", "Grey, dense logs of BarkReach ironbark (Woodcutting 68). An axe bounces off a standing one, and the bark lurkers grow in the old ones round a heart of grey wood.", "Cut or hold ironbark logs.", { item: ["ironbark_logs", "heartwood"] }, { item: "ironbark_logs" }),
  card("resource_antler", "Greatstag antler", "resource", "A branch of antler from a BarkReach greatstag. Fletchers tip arrows with it; the Federation makes other things.", "Hold a greatstag antler.", { item: ["stag_antler"] }, { item: "stag_antler" }),
  card("resource_ash_heart", "Ash hearts and burnt tokens", "resource", "What's left in one of the Burned when it stops: a knot of ash that stays warm for days, and a bronze token charred past reading, a number that used to mean something.", "Take an ash heart or a burnt token from the Burned.", { item: ["ash_heart", "burnt_token"] }, { item: "ash_heart" }, { order: "ember" }),
  card("resource_writ", "A writ of passage", "resource", "Stamped with the closed eye: the bearer may pass the Regiment's lines. It has your Friend's number on it. You did not give it to them.", "Carry a writ of passage.", { item: ["writ_of_passage"] }, { item: "writ_of_passage" }, { faction: "raria" }),
  // ---------- Quests ----------
  ...([["west_watch", "The Western Watch"], ["rrr_truce", "Papers of Passage"], ["wise_friends_law", "The Wise Friend's Law"], ["cog_ledger", "The Ledger of Names"], ["cog_reliquary", "What the Dusk Lost"], ["cog_federation", "Eyes on the Federation"],
    ["fff_truce", "The Gate Question"], ["fff_cannon", "Fortunately, We Built a Solution"], ["fff_toaster", "The Toaster Argument"], ["fff_rangers", "Whispers in BarkReach"], ["fff_sabotage", "Powder and Paper"], ["barkreach_heartwood", "Heartwood"], ["candlemere_tithe", "The Candlemere Tithe"], ["heartwood_elder", "The Ironbark Elder"],
    ["hollow_king", "The Hollow King"], ["pilgrims_road", "The Pilgrim's Road"], ["ringmasters_signet", "The Ringmaster's Signet"], ["maidens_truce", "The Maidens' Truce"], ["howling_vault", "What the Stones Keep"]] as const).map(([id, name]) =>
    card(`quest_${id}`, name, "quest", `${name}: done, and written down.`, "Complete the quest.", { quest: id }, { color: id.startsWith("fff") ? "#2f7d68" : id.startsWith("cog") || id === "rrr_truce" || id === "wise_friends_law" ? "#3b2a52" : "#8a2f2b" }, id.startsWith("fff") ? { faction: "fff" } : id.startsWith("cog") || id === "rrr_truce" || id === "wise_friends_law" ? { faction: "raria" } : {})),
];
const CARD_MAP = new Map(CARDS.map(card => [card.id, card]));
export const cardDef = (id: string) => CARD_MAP.get(id);
/** Whether an Order's content is open: its leader met (the dusk's prior, the commanders), or the faction's. */
export function orderOpen(game: Game, order: OrderId | "fff" | "raria" | "watcher" | undefined) {
  if (!order) return true;
  if (order === "fff") return (game.player.questData.met_fff ?? 0) >= 1;
  if (order === "raria") return (game.player.questData.met_raria ?? 0) >= 1;
  if (order === "watcher") return (game.player.questData.met_watcher ?? 0) >= 1;
  return metOrder(game.player.questData, order);
}
const owns = (game: Game, id: string) => isItem(id) && (count(game.player, id) > 0 || game.player.bank.some(slot => slot.id === id) || Object.values(game.player.equipment).includes(id));
/** Whether the card's condition holds right now (found cards stay found regardless). */
export function cardCondition(game: Game, card: CardDef): boolean {
  const p = game.player, u = card.unlock;
  if (card.order && !orderOpen(game, card.order)) return false;
  if (u.met && orderOpen(game, u.met) && !u.near && !u.item) return true;
  if (u.met && !orderOpen(game, u.met)) return false;
  if (u.talk?.some(id => p.talked[id])) return true;
  if (u.quest && questDone(game, u.quest)) return true;
  if (u.region && p.visited[u.region]) return true;
  if (u.kill && (p.killLog[u.kill] ?? 0) >= 1) return true;
  if (u.item?.some(id => owns(game, id))) return true;
  if (u.near && Math.max(Math.abs(p.x - u.near.x), Math.abs(p.y - u.near.y)) <= u.near.r) return true;
  if (u.flag && (p.questData[u.flag] ?? 0) >= 1 && (!u.skill || level(game, u.skill[0]) >= u.skill[1])) return true;
  if (u.rarian && p.rarian && (!u.skill || level(game, u.skill[0]) >= u.skill[1])) return true;
  return false;
}
export const cardFound = (game: Game, id: string) => (game.player.cards[id] ?? 0) >= 1;
export const cardsFound = (game: Game) => CARDS.filter(card => cardFound(game, card.id)).length;
/** Every twenty ticks: anything whose condition holds now is found, announced, and kept. */
export function codexTick(game: Game) {
  const p = game.player, day = Math.max(1, Math.floor(Date.now() / 86_400_000));
  for (const card of CARDS) {
    if (p.cards[card.id]) continue;
    if (!cardCondition(game, card)) continue;
    p.cards[card.id] = day;
    message(game, `New Adventurer Card: ${card.name}.`, "quest"); sound(game, "quest");
    if (card.id === "enemy_the_burned") p.questData.card_burned = 1;
  }
}
/** Cards by kind, for the collection: found ones first within a kind, then the hints. */
export const cardsOfKind = (kind: CardKind) => CARDS.filter(card => card.kind === kind);
export const CARD_KINDS = Object.keys(CARD_KIND_NAMES) as CardKind[];
