/**
 * The Friends' words. One big well that friend.ts draws from, so lines can be added without touching the logic:
 *   VOICES    what each family says to the things that happen (region, creature, grave, fight, rare find…)
 *   SKILLS    what each family says while working a skill (chopping, fishing, smithing, brewing, praying…)
 *   CHATTER   random talk: a line now and then for no reason, in each family's manner, plus the odd shared one
 *   WEATHER   remarks keyed to the sky, with family colouring
 * Families: 0 Skeleton, 1 Mask, 2 Family, 3 Cellular, 4 Asymmetry, 5 Hoverer, 6 Colossus, 7 Sparkling, 8 Hollow.
 * {name} is a named thing, {n} a count, {skill} a skill's name, {region} where you are, {friend} your Friend's name.
 */
import type { Skill } from "./data.ts";

export type FriendEvent =
  | "region" | "revisit" | "night" | "rain" | "creature" | "creature_again" | "dragon" | "dragon_again" | "undead" | "grave" | "altar" | "statue"
  | "fight" | "hurt" | "rare" | "quest" | "boss" | "death" | "mount" | "fellowship" | "mastery" | "tired" | "mine" | "chop" | "bones" | "underground" | "mountain" | "sea" | "hollow"
  | "mixture" | "outfit" | "friend_near" | "idle" | "levelup" | "full_pack" | "coins" | "shop" | "bank" | "pet" | "storm" | "fog" | "dawn" | "snow" | "lava" | "swamp" | "desert" | "village" | "ruin" | "water";
export type Voice = Partial<Record<FriendEvent, readonly string[]>>;

export const VOICES: readonly Voice[] = [
  // ---------- 0 Skeleton: dry, morbid, a little sarcastic ----------
  { region: ["{name}. Looks like somewhere people die.", "{name}. I've seen worse. I've been worse.", "{name}. Smells of fresh graves. Promising."], revisit: ["{name} again. Still standing, both of us.", "{name}. Back for more. Can't think why."],
    night: ["Dark. Good. Fewer people staring.", "Night. My favourite colour.", "The dark suits me. Everything suits me, I've no skin to clash with."], rain: ["At least I don't have to worry about getting wet.", "Rain. It'll rust something. Not me."],
    storm: ["Thunder. The dead love a bit of drama.", "Lightning. Finally, some good light for my cheekbones."], fog: ["Fog. Can't see my hand in front of my face. Haven't got much face."], dawn: ["Morning. Overrated."], snow: ["Snow. I'm already the right colour for it."],
    creature: ["Is that a {name}? Friends of mine?", "A {name}. It looks hungry. Not my problem.", "A {name}. Go on, then. Bite me. Good luck."], creature_again: ["Another {name}. We know how this ends.", "{name} number {n}. I've stopped counting. Lie."],
    dragon: ["A dragon. Well. That's a lot of bones.", "Dragon. Imagine the size of its skull."], dragon_again: ["Another one.", "Another dragon. Yawn. Don't tell it I said that."], undead: ["Friends of mine?", "They've let themselves go.", "Cousins. Distant. Very distant."],
    grave: ["Finally. Someone who planned ahead.", "Nice plot. Quiet neighbours.", "Somebody's home. Don't knock."], altar: ["Bones go here. I know how this feels.", "An altar. Bring a bone, make a wish."], statue: ["The beard's a nice touch.", "Old Friend. He looks like he'd keep a secret."],
    fight: ["Try not to hit anything I'd miss.", "This again.", "Mind my ribs. I'm fond of them."], hurt: ["I've seen worse.", "That's going to show.", "Ow. Allegedly."], rare: ["Shiny. Put it somewhere I can see it.", "Ooh. Treasure. I was a treasure once. In a box."],
    quest: ["Done. Where do they bury the thanks?", "Finished. Nobody died. Disappointing."], boss: ["It's down. Stay down. I would.", "That was big. It's small now."], death: ["Well. That's one way to see the place.", "Death. Been there. Still there, technically."],
    mount: ["It has more legs than I have. Fine.", "Giddy up. Gently. I rattle."], fellowship: ["A company. Mine's a long story.", "Fellows. Good. Someone to carry me when I fall apart."], mastery: ["Ninety-nine. Took us long enough.", "Ninety-nine. Put it on my stone."],
    levelup: ["A level. Lovely. Bones don't grow, you know.", "Level up. Try not to let it go to your head. I keep mine in a bag."], tired: ["Walking's fine. Walking's dignified.", "Out of puff. I've no lungs, so that's your fault."],
    mine: ["Rocks. Harder than bones. Barely.", "Mining. Like digging a grave, but up."], chop: ["A tree. It won't feel a thing.", "Timber. The tree's dead. We have that in common."], bones: ["These belong somewhere.", "Bones. Mind how you carry them. I would."],
    underground: ["This feels familiar.", "Home, almost.", "Nice and dark. Nice and damp. Nice."], mountain: ["Big rock. Old rock.", "Thin air. Doesn't bother me."], sea: ["The sea. Wet. No thank you.", "Water. I'd sink. I'd sink well, though."],
    hollow: ["…", "Something here knows my name.", "I'm told I'd fit in here. I'd rather not find out."], swamp: ["Bog. Good for preserving things. Ask me how I know."], desert: ["Sand. Gets everywhere. Even in me."], lava: ["Lava. Bones don't burn well. Don't test it."],
    mixture: ["Marrow. Yes. That's the stuff."], outfit: ["We're really wearing this?", "That's a look. Not a good one. A look."], friend_near: ["Another one of us. Act natural.", "Company. Keep your bones to yourself."],
    village: ["A village. People. Try not to frighten them. Leave that to me."], ruin: ["Ruins. Somebody's dead house. I feel at home."], water: ["Water. Don't fall in. I can't swim and I can't drown. Awkward."],
    full_pack: ["Pack's full. I'd offer to carry some, but."], coins: ["Coins. Can't take them with you. I checked."], shop: ["A shop. Don't buy anything with a pulse."], bank: ["The bank. Safer than a grave. Just."], pet: ["A pet. It's going to chew on me, isn't it."],
    idle: ["…", "Hmm.", "Still here.", "Nothing to report. Unless you count the existential dread.", "I had a thought. It's gone. Like most of me.", "Do you ever think about how many bones you're carrying right now? I do."] },
  // ---------- 1 Mask: says little, means more ----------
  { region: ["{name}.", "{name}. New faces.", "{name}. Watch how they look at you."], revisit: ["{name}. We've worn this one before.", "{name} again. Same faces."],
    night: ["Night suits a mask.", "Dark. The face can rest."], rain: ["…", "Rain. The paint runs."], storm: ["Thunder. Good cover."], fog: ["Fog. Nobody sees anyone. Perfect."], dawn: ["Light. Put the face on."], snow: ["White. A blank face."],
    creature: ["A {name}. Keep still.", "{name}. It hasn't seen us.", "{name}. It's looking for a face. Don't give it one."], creature_again: ["{name}. Again.", "{name}. We know this one."],
    dragon: ["A dragon. Don't blink.", "Dragon. Even I'd look away."], dragon_again: ["…again.", "Another. It remembers us."], undead: ["They wear faces too. Badly.", "No face left on those."],
    grave: ["Someone's face is under there.", "A grave. They stopped pretending."], altar: ["Faces come off here, they say.", "An altar. Leave something. Not the mask."], statue: ["A face that stayed.", "He never took his off either."],
    fight: ["Watch its eyes.", "…now."], hurt: ["…that one got through.", "A crack."], rare: ["Ours now.", "…nice."], quest: ["Done. Say nothing.", "Finished. Keep the face straight."], boss: ["It had a face. Now it doesn't.", "Down."],
    death: ["We were seen.", "…the mask slipped."], mount: ["High. Good.", "Faster. Fewer looks."], fellowship: ["A company of masks.", "More faces. Fine."], mastery: ["Ninety-nine. Nobody saw it coming.", "Ninety-nine. Keep it quiet."],
    levelup: ["Stronger. Show nothing.", "A level. Don't smile. Can't, anyway."], tired: ["Slow is quiet.", "Walk. Nobody runs in a mask."], mine: ["Stone keeps secrets.", "Dig. Quietly."], chop: ["The trees are listening.", "…"], bones: ["…", "Bones. The last face."],
    underground: ["Dark. Good.", "Nobody looks down here."], mountain: ["Thin air. Thin faces.", "High. Far from eyes."], sea: ["The sea has no face.", "Water shows your face. Don't look."], hollow: ["It's looking for one of us.", "…don't answer it.", "It wears nothing. It wants to."],
    swamp: ["The bog keeps what it's given."], desert: ["The sand wears everything smooth. Faces too."], lava: ["Fire. The one thing a mask fears."],
    mixture: ["Many faces. All mine."], outfit: ["A disguise. Finally.", "…better."], friend_near: ["A face I know.", "One of us. They know it too."], village: ["People. Faces. Keep yours."], ruin: ["Whoever lived here took their faces with them."], water: ["Still water. Don't look in."],
    full_pack: ["Full. Choose."], coins: ["Coins. Quiet ones."], shop: ["A shop. Say little. Pay less."], bank: ["The bank. Faces behind bars. Good."], pet: ["It knows which face is real. Clever."],
    idle: ["…", "…", "Hm.", "…listen.", "Someone's watching. Someone's always watching.", "…no."] },
  // ---------- 2 Family: warm, fussing, talks about home ----------
  { region: ["{name}! Oh, look at it.", "{name}. Let's find somewhere warm.", "{name}! Have we got everything? Did we lock the bank?"], revisit: ["{name} again. Feels like coming home.", "{name}! Our old haunt."],
    night: ["Getting dark. Have we eaten?", "Night. Somebody's wondering where we are."], rain: ["Rain! We should be indoors with soup.", "Oh, you'll catch your death. Hood up."], storm: ["Thunder! Count the seconds. Come away from the trees."], fog: ["Fog. Hold my hand, we'll lose each other."], dawn: ["Morning! Breakfast first, adventures after."], snow: ["Snow! Scarf. Where's your scarf?"],
    creature: ["A {name}! Careful, love.", "There's a {name}. Stay close.", "A {name}. Don't you dare pet it."], creature_again: ["Another {name}. We've managed worse.", "{name} again. Honestly, they're like relatives."],
    dragon: ["A DRAGON. Hold my hand.", "Oh my days. A dragon. Smile, maybe it's friendly."], dragon_again: ["Another one. Deep breath.", "Another dragon. We really should write home about this."], undead: ["Those poor things. Somebody's family.", "They just want a hug. Don't give them one."],
    grave: ["Somebody's remembered. That's nice.", "A grave. Say something kind."], altar: ["Say something for the folks at home.", "An altar. Light a candle for Grandma."], statue: ["He looks like my grandad.", "The Old Friend. Lovely beard. Trustworthy beard."],
    fight: ["Be careful! I mean it!", "Watch yourself! Watch it! Watch everything!"], hurt: ["Oh! Are you all right?", "Ow! Sit down a minute. No? Fine. Be careful."], rare: ["Look what we found! We're keeping it.", "Treasure! This goes on the mantelpiece."],
    quest: ["We did it. I'm so proud.", "Finished! Tell everyone. Tell the baker."], boss: ["It's over. Come here.", "We did that. Us. I need a sit down."], death: ["We're all right. We're all right.", "Oh, that was awful. Never again. Well. Maybe again."],
    mount: ["Hello, you lovely thing.", "A horse! Does it have a name? It needs a name."], fellowship: ["A family that picked us. Imagine.", "Fellows! We'll have them round."], mastery: ["Ninety-nine! Wait till I tell everyone.", "Ninety-nine! Oh, I'm welling up."],
    levelup: ["A level! You clever thing.", "Look at you, growing up."], tired: ["Let's just walk. No rush.", "Take a breather. Have something to eat."], mine: ["Mind your fingers.", "Careful with that pick."], chop: ["Firewood for later.", "Mind it doesn't fall on you!"], bones: ["Bury them nicely.", "Poor thing. We'll put them to rest."],
    underground: ["It's damp. Don't catch a chill.", "Dark down here. Mind the steps."], mountain: ["What a view. Mind the edge.", "High up! Don't look down. I looked down."], sea: ["Smell that air.", "The seaside! We should have brought sandwiches."], hollow: ["I don't like it here. Let's not stay.", "This place is cold in the wrong way. Stay close."],
    swamp: ["Boots on. It's boggy."], desert: ["Hat on. Water. Did we bring water?"], lava: ["Back! Back from the edge! Honestly."],
    mixture: ["Oh, that's warm. That's lovely."], outfit: ["Very smart. Turn round.", "Oh, it suits you. It does. Mostly."], friend_near: ["Another Friend! Say hello.", "Company! Be nice."], village: ["A village! Let's see who's about.", "People! Wave. Be polite."], ruin: ["Somebody lived here. Sad, isn't it."], water: ["Don't go in, it's freezing."],
    full_pack: ["Pack's full. Shall we bank some? We should bank some."], coins: ["Coins! Put them away safe."], shop: ["A shop. Don't spend it all."], bank: ["Bank it. Bank it now."], pet: ["Oh, hello, little one! Who's a good one?"],
    idle: ["Hmm.", "Are you hungry?", "Nice day for it.", "I wonder what the others are up to.", "We should write home.", "Did you remember to eat? Eat something.", "I like it here. Don't you like it here?"] },
  // ---------- 3 Cellular: curious, scientific, counts things ----------
  { region: ["{name}. New sample.", "{name}. Note the flora.", "{name}. Different soil. Interesting."], revisit: ["{name}. Same as last time, roughly.", "{name}. Control group."],
    night: ["Light levels dropping. Noted.", "Night. Nocturnal observation begins."], rain: ["Precipitation. Good for the fungi.", "Rain. Measure it. No? Fine."], storm: ["Electrical activity. Fascinating. Dangerous. Fascinating."], fog: ["Visibility reduced. Proceed by touch."], dawn: ["Photosynthesis resumes."], snow: ["Crystalline. Each one different. Allegedly."],
    creature: ["A {name}. Observe it.", "Specimen: {name}.", "A {name}. Note the gait."], creature_again: ["{name}, specimen {n}.", "{name}. Population stable."],
    dragon: ["A dragon. The size of it. Measure it later.", "Dragon. Endothermic? Exothermic? Both?"], dragon_again: ["Another. The population's healthy.", "Dragon. Sample two. Or ten."], undead: ["Dead tissue, still moving. Fascinating. Horrible.", "Reanimation. The mechanism is unclear. Keep it that way."],
    grave: ["Decomposition. Nature's own apothecary.", "A grave. Rich soil."], altar: ["Interesting residue.", "An altar. Something reacts here."], statue: ["Lichen on the beard. Old.", "The Old Friend. Erosion suggests centuries."],
    fight: ["Watch its pattern.", "Observe. Then strike. Then observe."], hurt: ["Tissue damage. Regenerating.", "Ow. Noted."], rare: ["Rare. One in how many?", "A rare find. Statistically unlikely. Delightful."],
    quest: ["Hypothesis confirmed. Reward collected.", "Done. Record the result."], boss: ["Big sample. Down.", "Apex specimen, neutralised."], death: ["Cell death. Temporary.", "Expired. Resumed."],
    mount: ["Four legs. Efficient.", "Quadruped. Faster. Good."], fellowship: ["A colony. Good.", "Group behaviour. Beneficial."], mastery: ["Ninety-nine. The curve finally flattens.", "Ninety-nine. Maximum observed."],
    levelup: ["Growth. Expected.", "A level. The data agrees."], tired: ["Energy reserves low. Walk.", "Glycogen depleted. Reduce speed."], mine: ["Good ore. Veins run that way.", "Mineral content high."], chop: ["Count the rings.", "Cellulose. Harvest."], bones: ["Calcium. Useful.", "Bones. Catalogue them."],
    underground: ["Humid. Things grow here.", "Subterranean. Note the moulds."], mountain: ["Thin air. Tall plants.", "Altitude. Fewer samples."], sea: ["Salt. Kelp. Pearlweed, if we're lucky.", "Marine. Everything's wet and alive."], hollow: ["Nothing grows here. Nothing. That's wrong.", "Zero growth. Zero. Record it and leave."],
    swamp: ["Fungi! Everywhere. Don't lick anything."], desert: ["Arid. Succulents. Sunthorn, ideally."], lava: ["Extremophiles would love this. We would not."],
    mixture: ["Division. I can feel it splitting."], outfit: ["Protective, presumably.", "Fibres. Natural. Adequate."], friend_near: ["Another of us. Compare notes.", "A second sample. Compare."], village: ["Settlement. Observe the population."], ruin: ["Ruins. Overgrown. Good samples."], water: ["Fresh water. Probably. Don't drink it."],
    full_pack: ["Capacity reached. Sort."], coins: ["Currency. Count it."], shop: ["Trade. Compare prices."], bank: ["Storage. Catalogue."], pet: ["A companion organism. Feed it."],
    idle: ["Hmm.", "Interesting.", "Noted.", "I counted the trees. Then I lost count. Then I counted again.", "Everything here is alive. Even the rocks, slowly.", "What would happen if we planted a sigil?"] },
  // ---------- 4 Asymmetry: lopsided, odd, funny by accident ----------
  { region: ["{name}. It's crooked. I like it.", "{name}. Hm. The left side's better.", "{name}. Nothing lines up. Home."], revisit: ["{name}, the second time. Or third. I lose count on one side.", "{name} again. Still leaning."],
    night: ["One eye says night. The other disagrees.", "Dark on the left. Darker on the right."], rain: ["Rain on the left. Dry on the right. Typical.", "Rain. It falls crooked. I approve."], storm: ["Lightning! It zigzags. My kind of weather."], fog: ["Fog. Can't tell my sides apart. Nothing new."], dawn: ["Sun's up. On one side."], snow: ["Snow. It settles unevenly. Good."],
    creature: ["A {name}. It's looking at my good side.", "A {name}. Wonky. Like me. I like it."], creature_again: ["{name}. It's leaning. Like me.", "Another {name}. Still crooked."],
    dragon: ["A dragon! Which end is the front?", "Dragon. Both ends look angry."], dragon_again: ["Another one. Still can't tell which end.", "Dragon again. It's lopsided too. Wings are different sizes. Look."], undead: ["They're falling apart. Relatable.", "Bits missing. I know the feeling."],
    grave: ["Crooked stone. My kind of stone.", "A grave. Slightly off. Perfect."], altar: ["It's off-centre. I approve.", "An altar. Lean on it. No, don't."], statue: ["His beard's longer on the left. Good.", "Old Friend. One eye higher than the other. We'd get on."],
    fight: ["Hit it with the heavy side.", "Swing wide. I always do."], hurt: ["Ow. The other side's fine.", "That hurt the good half."], rare: ["Ooh. Lopsided luck.", "Treasure! It's uneven. It's perfect."],
    quest: ["Done. Mostly. The good half.", "Finished. Crookedly. Still counts."], boss: ["It fell over. So do I, sometimes.", "Down. Sideways. Down."], death: ["That tipped me over.", "Fell. Got up. The usual."],
    mount: ["It walks straighter than I do.", "A horse. It'll list to one side. Mine."], fellowship: ["A company. I'll stand at the odd end.", "Fellows. Finally, someone to lean on."], mastery: ["Ninety-nine. Sideways, but we got there.", "Ninety-nine. The number's lopsided too. Look at it."],
    levelup: ["A level. Lopsided progress is still progress.", "Up a level. Diagonally."], tired: ["Walk. Lean into it.", "Tired on one side. Hop."], mine: ["Rocks are all lumpy. Finally, company.", "Mining. The pick's crooked. Or I am."], chop: ["It'll fall left. Trust me.", "Timber! Crooked timber. Best kind."], bones: ["Mine don't match either.", "Bones. Odd ones. I'll take them."],
    underground: ["It slopes. Everything slopes.", "Dark and uneven. Cosy."], mountain: ["A hill with ideas.", "Mountains. Nature's lopsided bits."], sea: ["The sea's level. Show-off.", "Waves. Finally something more uneven than me."], hollow: ["Everything here is wrong in the same direction.", "Even the crookedness is crooked here. I don't like it."],
    swamp: ["Squelch on the left. Squelch on the right. Balanced, for once."], desert: ["Dunes. Lopsided hills. Lovely."], lava: ["Hot on one side. Very hot on the other."],
    mixture: ["Lopsided? More lopsided. Perfect."], outfit: ["Does it come in uneven?", "It hangs funny. Good."], friend_near: ["Another one! Stand on my good side.", "A Friend. Which side's their good side?"], village: ["A village. Nothing's straight. I love it."], ruin: ["Ruins. Everything's fallen one way. Mine."], water: ["Water. My reflection's the right way round for once."],
    full_pack: ["Full. The left pocket, anyway."], coins: ["Coins. Odd number, I hope."], shop: ["A shop. Ask for the wonky one. Cheaper."], bank: ["Bank. They never stack my things straight."], pet: ["A pet! It's lopsided. No it isn't. Yes it is."],
    idle: ["Hmm?", "Whoa.", "…what?", "I'm standing on a slope. I'm always standing on a slope.", "Which way's north? Which way's my left?", "Did that tree just lean? No? It did."] },
  // ---------- 5 Hoverer: energetic, curious, always looking further ----------
  { region: ["{name}! What's over there?", "{name}. Let's see all of it.", "{name}! Which way first? Every way. Every way first."], revisit: ["{name} again! Did we check the far side last time?", "{name}! I bet there's a bit we missed."],
    night: ["It's dark. Everything's an adventure in the dark.", "Night! Stars! Can we go up there?"], rain: ["Rain! Race you to the next roof.", "Rain! I'll float over the puddles."], storm: ["Lightning! Did you see that? DID YOU SEE THAT?"], fog: ["Fog! Everything's a surprise now."], dawn: ["Morning! Go go go!"], snow: ["SNOW. We're going up the mountain. Now."],
    creature: ["Wait. What's that? A {name}!", "A {name}! Let's get closer. No? A bit closer."], creature_again: ["{name}! Let's go round it. Or over.", "{name} again! Different one? Same one? Who cares!"],
    dragon: ["Is that a DRAGON?!", "DRAGON. Dragon dragon dragon."], dragon_again: ["Another dragon! Can we keep one?", "Dragon! I could fly like that. Nearly. A bit."], undead: ["They're so slow. We could just… float.", "Skeletons! They can't jump. Ha!"],
    grave: ["Quiet here. Let's not stay.", "Graves. Shh. Okay, quietly, what's over there?"], altar: ["Ooh. What does it do?", "An altar! Touch it. Touch it!"], statue: ["We could get up there.", "I can see up his nose from here. Hover advantage."],
    fight: ["Go go go!", "Hit it! Hit it from above!"], hurt: ["Ow! Okay. Moving!", "Ouch! Float faster!"], rare: ["Look! LOOK!", "Shiny! Shiny shiny shiny!"],
    quest: ["Done! What's next? What's NEXT?", "Finished! Where to now? Everywhere?"], boss: ["We did it! Did you see that?!", "DOWN! It's down! We did that!"], death: ["…okay. Okay. Again.", "Oof. Right. Floating back up."],
    mount: ["Faster! Yes!", "A horse! It's like floating but with legs!"], fellowship: ["A company! More people to show things to.", "Fellows! Can they fly? Teach them to fly."], mastery: ["Ninety-nine! Is there a hundred?", "Ninety-nine! What's past ninety-nine? Let's find out!"],
    levelup: ["Level! Higher! Higher!", "Up a level! Up up up!"], tired: ["Okay… maybe we walk.", "Puffed. Walking. Boo."], mine: ["Boring. What's under it, though?", "Rocks. What's behind the rocks? Dig faster."], chop: ["Timber! Was that right?", "Chop chop! Can we climb it first?"], bones: ["Eugh. Carry them anyway.", "Bones! Whose? Doesn't matter. Mine now."],
    underground: ["It's dark. I love it. I hate it.", "Caves! What's at the end? Let's see the end!"], mountain: ["We could get up there. We should get up there.", "Higher! The top! Is there a top?"], sea: ["I can see something! Out past the isles!", "The sea! What's across it? Let's cross it!"], hollow: ["I don't want to float here.", "Something's pulling. Downwards.", "This place is heavy. I hate heavy."],
    swamp: ["Squelchy! Float over it. Ha!"], desert: ["Sand! What's over the next dune? And the next?"], lava: ["Hot! Hot hot hot! Pretty, though."],
    mixture: ["I'm not touching the ground. I'M NOT TOUCHING THE GROUND."], outfit: ["Ooh. Do I look fast?", "New clothes! Do they flap? Make them flap."], friend_near: ["Hi! HI!", "Another Friend! Race you!"], village: ["A village! People! Shops! Roofs to float over!"], ruin: ["Ruins! What's inside? What's under? What's on top?"], water: ["Water! Skim it! Skim it!"],
    full_pack: ["Full! Drop something! Not that! Not that either!"], coins: ["Coins! Spend them! On what? Anything!"], shop: ["A shop! What's new? What's NEW?"], bank: ["The bank. Boring. Quick. Go!"], pet: ["A pet! Can it fly? Teach it!"],
    idle: ["What's over there?", "Hmm!", "Did you hear that?", "I'm bored. Let's go somewhere. Anywhere.", "What's the furthest we've ever been? Let's beat it.", "Is that a path? That's a path. Let's take it."] },
  // ---------- 6 Colossus: slow, blunt, physical ----------
  { region: ["{name}. Big.", "{name}. Good ground.", "{name}. Hm."], revisit: ["{name}. Been here.", "{name}. Again. Fine."],
    night: ["Dark. Fine.", "Night. Sleep standing."], rain: ["Wet.", "Rain. Doesn't matter."], storm: ["Loud.", "Thunder. Louder than me. Barely."], fog: ["Can't see. Walk anyway."], dawn: ["Light."], snow: ["Cold. Fine."],
    creature: ["A {name}. I could fight that.", "{name}. Small."], creature_again: ["{name}. Again. Fine.", "{name}. Still small."],
    dragon: ["Dragon. Big. Good.", "Dragon. Finally. Something my size."], dragon_again: ["Another one. I could fight that too.", "Dragon. Again. Good."], undead: ["Thin. Snap easy.", "Bones. Brittle."],
    grave: ["Small.", "A hole. Small hole."], altar: ["Stone. Good stone.", "Altar. Heavy. Good."], statue: ["Beard. Good.", "Stone man. Smaller than me."],
    fight: ["Hit it.", "Hit it harder."], hurt: ["Hm.", "Scratch."], rare: ["Now that's a weapon.", "Mine.", "Shiny. Heavy. Good."],
    quest: ["Done.", "Finished. Next."], boss: ["Down.", "Big. Was big."], death: ["Up.", "Fell. Up again."],
    mount: ["Strong one.", "Horse. Carries me. Brave horse."], fellowship: ["Good. More hands.", "Fellows. Good. Lift things."], mastery: ["Ninety-nine. Big number.", "Ninety-nine. Good."],
    levelup: ["Bigger.", "Stronger. Good."], tired: ["Walk, then.", "Slow. Fine."], mine: ["Good stone.", "Rock. Break it."], chop: ["Big tree. Good.", "Tree. Push it. No? Chop, then."], bones: ["Small bones.", "Bones. Light."],
    underground: ["Too small.", "Low roof. Duck."], mountain: ["Big.", "Mountain. Good. Climb it."], sea: ["Big water.", "Sea. Can't punch it."], hollow: ["Cold. Don't like cold.", "Hollow. Empty. Fill it."],
    swamp: ["Sinking. Walk faster."], desert: ["Hot. Heavy sand."], lava: ["Hot rock. Good rock. Don't touch."],
    mixture: ["Bigger. Good."], outfit: ["Tight.", "Clothes. Fine."], friend_near: ["One of us.", "Friend. Small."], village: ["Houses. Small doors."], ruin: ["Broken. Was big once."], water: ["Water. Wet."],
    full_pack: ["Full. Carry more. Can't. Hm."], coins: ["Coins. Heavy. Good."], shop: ["Shop. Buy big things."], bank: ["Bank. Keep things."], pet: ["Small thing. Don't step on it."],
    idle: ["Hm.", "…", "Good.", "Hungry.", "Big rock over there. Good rock.", "Could lift that. Could lift most things."] },
  // ---------- 7 Sparkling: bright, delighted, can't contain itself ----------
  { region: ["{name}! It's gorgeous!", "{name}! Oh, the light here!", "{name}! Look how it catches the sun!"], revisit: ["{name} again! Still sparkly.", "{name}! I missed the light here!"],
    night: ["Stars! We should stay up.", "Night! Every lamp's a jewel!"], rain: ["Rain! Everything shines after!", "Raindrops! Tiny diamonds! Thousands of them!"], storm: ["LIGHTNING! The sparkle of the gods!"], fog: ["Fog! Soft focus. Very flattering."], dawn: ["Dawn! Gold everywhere! Look!"], snow: ["Snow! It glitters! IT GLITTERS!"],
    creature: ["A {name}! Isn't it something?", "A {name}! Look at its little eyes shine!"], creature_again: ["Another {name}! Hello!", "{name}! Still gorgeous. Still bitey."],
    dragon: ["A dragon! The scales! The SCALES!", "Dragon! Imagine the shimmer up close. From far away. Far away is fine."], dragon_again: ["Another one! They're all so shiny.", "Dragon! Each one shinier than the last!"], undead: ["They need a bit of sparkle. And sleep.", "Oh, they're dull. Poor things."],
    grave: ["Flowers would help here.", "A grave. Leave something bright."], altar: ["Candles! Light them all!", "An altar! Make it glow!"], statue: ["He'd look lovely with a bit of gold leaf.", "The Old Friend! Polish him!"],
    fight: ["Make it dazzling!", "Shine on it! Hit it! Shine!"], hurt: ["Ow! That's going to bruise. In a pretty colour.", "Ouch! My sparkle!"], rare: ["It SHINES! Oh, we're keeping that.", "Treasure! Hold it up to the light!"],
    quest: ["Done! Fireworks! Where are the fireworks?", "Finished! Confetti! Somebody!"], boss: ["We did it! Oh, I'm glowing.", "Down! And what a show!"], death: ["Even stars fall. Up again.", "Oh! Faded. Back! Brighter!"],
    mount: ["Ribbons! It needs ribbons.", "A horse! Braid its mane! Beads!"], fellowship: ["A company! We'll glitter together.", "Fellows! A constellation!"], mastery: ["Ninety-nine! We're brilliant. Literally.", "Ninety-nine! Shine shine shine!"],
    levelup: ["A level! Sparkle! Sparkle!", "Up! Brighter! Yes!"], tired: ["A stroll, then. Sparkle slowly.", "Puffed. Glow gently."], mine: ["Gems! Please let there be gems.", "Mining! Something shiny, please please please."], chop: ["Oh, the sawdust catches the light.", "Timber! The leaves flutter so prettily!"], bones: ["Not very sparkly, those.", "Bones. Dull. Bury them with a flower."],
    underground: ["Dark! I'll light the way.", "Caves! Crystals? Please crystals."], mountain: ["Snow! It glitters!", "Peaks! Catching the dawn! Oh!"], sea: ["Look at the light on the water!", "The sea! A million sparkles!"], hollow: ["It eats the light. I don't like it.", "Dim. Dim dim dim. Let's go."],
    swamp: ["Oh, it's murky. But look, the fireflies!"], desert: ["Sand! Every grain a glint!"], lava: ["LAVA. Oh. Oh, the glow. From here, though."],
    mixture: ["I'm fizzing! I'm actually fizzing!"], outfit: ["Oh, that's fabulous.", "Darling, the colour on you!"], friend_near: ["Another Friend! Twinkle at them!", "Company! Shine together!"], village: ["A village! Lamps! Windows! Lovely!"], ruin: ["Ruins. Moody. Dramatic. I love it."], water: ["Water! Reflections! Twice the sparkle!"],
    full_pack: ["Full! Of lovely things!"], coins: ["Coins! Gold! Shiny gold!"], shop: ["A shop! Anything with a shimmer, please."], bank: ["The bank! My treasures! Hello, treasures!"], pet: ["A pet! Oh, its little eyes! Twinkly!"],
    idle: ["Ooh!", "Whoa.", "Pretty.", "Everything's so pretty. Isn't it? Isn't it?", "I think I'm glowing a bit. Am I glowing?", "Look at the light. Just look at it."] },
  // ---------- 8 Hollow: quiet, strange, knows things it shouldn't ----------
  { region: ["{name}. It's thinner here.", "{name}. Something underneath remembers us.", "{name}. The ground hums a different note."], revisit: ["{name}. The echo's still here.", "{name} again. It remembers."],
    night: ["The dark's closer. Good.", "Night. The thin hours."], rain: ["It falls through me.", "Rain. It doesn't touch what I am."], storm: ["Lightning. Something flinches, far below."], fog: ["Fog. The world's not sure it's there. I know the feeling."], dawn: ["Light. It pushes."], snow: ["Snow. Cold like home. Almost."],
    creature: ["A {name}. It can't see what I am.", "{name}. It smells the cold on me."], creature_again: ["{name}. It still can't.", "Another {name}. They never learn what I am."],
    dragon: ["A dragon. Older than me. Just.", "Dragon. It knows. Look at it."], dragon_again: ["Another. They don't like what I am.", "Dragon. It turns away. Wise."], undead: ["They almost got there. Almost.", "Half-made. Poor things."],
    grave: ["Not empty. They never are.", "A grave. Something's listening under it."], altar: ["It hums. Can't you hear it?", "An altar. It's connected. To what, I won't say."], statue: ["He's not looking at you. He's looking at me.", "The Old Friend. He knew. I think he knew."],
    fight: ["Let it come.", "Through it. Not round."], hurt: ["It went through. Mostly.", "A hole. Another one."], rare: ["This was lost. Now it isn't.", "Found. It was waiting."],
    quest: ["Finished. Something noticed.", "Done. The echo changed pitch."], boss: ["It's gone where I came from.", "Down. I know where it went."], death: ["Not gone. Never gone.", "Back. I always come back."],
    mount: ["It can feel the cold in me. Brave thing.", "It shivers under me. Still carries me."], fellowship: ["A company. They don't know what they've let in.", "Fellows. They'll learn."], mastery: ["Ninety-nine. The edge of something.", "Ninety-nine. Thin, up here."],
    levelup: ["Deeper.", "A level. The hollow widens."], tired: ["Walk. The ground doesn't mind.", "Slow. The dark can wait."], mine: ["There's a hollow under the hollow.", "Dig. Carefully. Something's down there."], chop: ["It screams, a little. You can't hear it.", "The tree remembers being planted."], bones: ["They want to go somewhere. I know the feeling.", "Bones. The shape of what's missing."],
    underground: ["Closer to home.", "Deeper. Yes.", "Down here the hum is a voice."], mountain: ["Thin air. Thinner me.", "High. Far from the hum."], sea: ["Nothing of mine out there.", "The sea doesn't know me. Good."], hollow: ["I'm home. We shouldn't be.", "It knows me. Keep walking.", "The crown's near. I can feel it weigh nothing."],
    swamp: ["Still water. Deep. Something looks back."], desert: ["Dry. The hollow hates dry."], lava: ["Fire. The opposite of me. Keep it there."],
    mixture: ["The shadows lean in. Let them."], outfit: ["A shape to hold onto.", "Clothes. Something to be seen in."], friend_near: ["One of us. Does it know?", "A Friend. It feels the cold. It stays. Good."], village: ["People. Warm. They look at me twice."], ruin: ["Ruins. Whoever built them went where I'm from."], water: ["Water. No reflection. Don't look."],
    full_pack: ["Full. Let something go. I know how."], coins: ["Coins. Weight. I have none of my own."], shop: ["A shop. They'll take my coin. Not my hand."], bank: ["The bank. Things kept. Things wait."], pet: ["It isn't afraid. Why isn't it afraid?"],
    idle: ["…", "Listen.", "It's quiet. Too quiet.", "The hum changed. Did you feel it?", "Something under us turned over.", "I was somewhere else a moment ago. I'm back."] },
];
/** The plain manner, for anything a family's voice leaves out. */
export const PLAIN: Voice = {
  region: ["{name}."], revisit: ["{name} again."], night: ["Night."], rain: ["Rain."], storm: ["A storm."], fog: ["Fog."], dawn: ["Morning."], snow: ["Snow."], creature: ["A {name}."], creature_again: ["Another {name}."], dragon: ["A dragon!"], dragon_again: ["Another dragon."], undead: ["Undead."],
  grave: ["A grave."], altar: ["An altar."], statue: ["A statue."], fight: ["Here we go."], hurt: ["Ow."], rare: ["Look at that."], quest: ["Done."], boss: ["It's down."], death: ["…"], mount: ["Up we get."], fellowship: ["A company."], mastery: ["Ninety-nine."], levelup: ["A level."],
  tired: ["Let's walk."], mine: ["Rock."], chop: ["Wood."], bones: ["Bones."], underground: ["Dark."], mountain: ["High."], sea: ["The sea."], hollow: ["…"], swamp: ["Bog."], desert: ["Sand."], lava: ["Lava."], mixture: ["Hm."], outfit: ["Hm."], friend_near: ["Hello."],
  village: ["A village."], ruin: ["Ruins."], water: ["Water."], full_pack: ["Full."], coins: ["Coins."], shop: ["A shop."], bank: ["The bank."], pet: ["A pet."], idle: ["Hmm."],
};

/** What a Friend says while you work a skill: a few per family per skill, and shared ones for everyone. */
export const SKILL_LINES: Partial<Record<Skill, { shared: readonly string[]; family: Partial<Record<number, readonly string[]>> }>> = {
  woodcutting: { shared: ["Mind the splinters.", "This one's thick.", "Logs. For the fire, or the bank."], family: { 0: ["Chop. The tree's dead already, it's just slow to admit it."], 2: ["Wrap up, there's a draught through the trees."], 5: ["Climb it first! No? Fine. Chop."], 6: ["Push it over. Faster."], 7: ["The chips catch the light. Pretty."], 8: ["It remembers being an acorn. Everything remembers."] } },
  mining: { shared: ["There's a vein in that.", "Chip, chip, chip.", "Ore. Good ore, maybe."], family: { 0: ["Rocks. Harder than bones. Barely."], 3: ["Note the strata."], 4: ["The lumpy ones are the good ones. I'd know."], 6: ["Good stone."], 7: ["Gems. Please. Gems."], 8: ["Something's under the rock. Under everything."] } },
  fishing: { shared: ["Patience.", "Something's nibbling.", "The water's calm. Suspiciously."], family: { 0: ["Fish. They've bones. I feel for them."], 2: ["Fresh fish for supper. Lovely."], 3: ["Note the species."], 5: ["This is slow. This is SO slow."], 6: ["Big fish. Punch it."], 7: ["The scales! Oh, the scales!"], 8: ["Something under the water is fishing too."] } },
  cooking: { shared: ["Don't burn it.", "Smells good. Mostly.", "Turn it. Turn it now."], family: { 0: ["Cook it well. I've no stomach, you have."], 2: ["A bit of salt. More salt. There."], 4: ["Burnt on one side. Perfect."], 6: ["Eat. Big. Good."], 7: ["Golden! Look at it!"], 8: ["Fire. The one thing I keep away from."] } },
  firemaking: { shared: ["There it goes.", "Warm hands.", "Keep it fed."], family: { 0: ["Fire. Bones don't burn well. Don't test it."], 2: ["Come and sit by it. Warm your feet."], 5: ["Sparks! Up! Up they go!"], 7: ["Fire! Dancing light! Oh!"], 8: ["It flinches from me. Good."] } },
  smithing: { shared: ["Hammer, don't tap.", "Red hot. Mind it.", "Another bar, another blade."], family: { 0: ["Metal. Harder than bones. Everything is."], 3: ["Note the temper."], 4: ["Hammer it crooked. It'll fly truer."], 6: ["Good. Heavy. Mine."], 7: ["The sparks! A fountain of them!"], 8: ["The metal remembers the fire. So do I."] } },
  crafting: { shared: ["Neat stitches.", "Nearly there.", "Careful with the needle."], family: { 0: ["Leather. I'd offer skin, but."], 2: ["My mother taught me that stitch. Not really. I wish."], 4: ["Uneven hem. Keep it."], 7: ["Add a bead. Add ten."], 8: ["Thread. Something to hold a shape together. I envy it."] } },
  fletching: { shared: ["Straight shafts.", "Feathers, then heads.", "That'll fly."], family: { 0: ["Arrows. Pointed bones, really."], 5: ["Make them fast. Faster than me. Try."], 6: ["Big arrows. Good."], 7: ["Red fletching. No, gold. GOLD."] } },
  magic: { shared: ["Sigils humming.", "Steady. Focus.", "The air's thick with it."], family: { 1: ["Magic. The best mask there is."], 3: ["Observe the sigil. Then burn it."], 7: ["Sparks! Real ones!"], 8: ["Spells keep their sigils for me. I don't ask why."] } },
  prayer: { shared: ["Light a candle.", "Say the words.", "The altar's warm."], family: { 0: ["Bones. Mine, someday. Not today."], 2: ["Say one for Grandma."], 7: ["The candles! All of them! Light them!"], 8: ["The altar hums. It knows me. It doesn't mind."] } },
  apothecary: { shared: ["Clean it first.", "Grind, don't bash.", "That'll brew."], family: { 0: ["A poison. Lovely. Keep it off me. I'm immune. I think."], 2: ["Soup. Basically soup. Dangerous soup."], 3: ["Observe the reaction. Fascinating."], 4: ["Stir it the wrong way. Trust me."], 5: ["Does it fizz? Make it fizz!"], 6: ["Drink. Strong."], 7: ["Look at the colour! Bottle the colour!"], 8: ["Something in that vial is awake."] } },
  thieving: { shared: ["Quietly.", "Hands soft.", "Don't get caught."], family: { 1: ["Light fingers. Lighter face."], 5: ["Grab it and float!"], 6: ["Sneaking. Hard. Big feet."], 8: ["Nobody sees me. Nobody could."] } },
  agility: { shared: ["Mind the gap.", "Don't look down.", "Breathe."], family: { 0: ["Jump. If I come apart, pick me up."], 4: ["Land on the good foot."], 5: ["Jump! Float! Jump!"], 6: ["Too small. Jump anyway."], 7: ["Leap! Graceful! Sort of!"] } },
  slayer: { shared: ["On task.", "Count them.", "The Warden'll want to know."], family: { 0: ["Slay. Make bones. I approve."], 6: ["Kill big things. Good."], 8: ["They go where I'm from. I'll show them the way."] } },
  hitpoints: { shared: ["Still standing.", "Breathe."], family: {} },
  presence: { shared: ["People remember that.", "They'll talk."], family: { 1: ["Known. Even in a mask."], 7: ["They'll remember the sparkle!"] } },
  sigilcraft: { shared: ["Press it in.", "Stone to sigil."], family: { 3: ["The stone changes state. Note it."], 8: ["The altar takes the stone. It takes other things too."] } },
  ranged: { shared: ["Steady aim.", "Loose."], family: { 5: ["From above! Shoot from above!"], 6: ["Arrows. Small. Hit anyway."] } },
  attack: { shared: ["Again.", "Strike true."], family: {} }, strength: { shared: ["Harder.", "Put your back in it."], family: { 6: ["Hit. Good."] } }, defence: { shared: ["Shield up.", "Hold."], family: {} },
};
/** Random talk for no reason at all: a line now and then, in each family's manner. */
export const CHATTER: readonly (readonly string[])[] = [
  ["I wonder who I was. I wonder if they'd mind.", "Everyone's a skeleton underneath. I'm just honest about it.", "My knees click. I don't have knees.", "You go on ahead. I'll haunt the back.", "People stare. Let them. Good bones.", "I'd kill for a sandwich. Can't eat. Kill anyway? No.", "Did you know I can whistle through my ribs? Don't ask me to."],
  ["…", "Who's behind the face? Who's behind that one?", "They think they know me. They know the mask.", "I had a different face yesterday. You didn't notice.", "Say less.", "Everyone's wearing one. Mine's just honest about it.", "…I like this one."],
  ["Did you remember to eat?", "We should visit Grandma. We don't have a Grandma. We should find one.", "Is it bedtime? It's nearly bedtime.", "I packed a spare scarf. You'll thank me.", "Nice people here. Mostly. That one, no.", "Write home. I'll dictate.", "What's for supper?"],
  ["I counted the stars. I lost count. I'll start again.", "Everything's made of smaller things. Even that.", "Hypothesis: it's going to rain. Evidence: it is raining.", "Note: the birds here sing a tone lower.", "What would happen if we planted a coin?", "The soil here is wrong. Good wrong.", "I've been dividing. Don't look."],
  ["My left side wants to go left. My right side agrees, which is new.", "Everything leans. Trees, houses, me. Especially me.", "Is the world crooked or is it just me? Both. Both is fine.", "I fell over. I'm fine. I meant to.", "Which way's up? Trick question. Diagonal.", "Nothing lines up. Beautiful.", "I'm symmetrical today. No I'm not."],
  ["What's over there? And there? And THERE?", "We should go higher. Everything's better from higher.", "I can see the sea from here. I can't. I want to.", "Race you to that tree. You lost. Again!", "Let's go somewhere we've never been. Now. Go!", "I'm bored. Say something. Say anything. Go!", "Can we fly today? Try. Jump. Try!"],
  ["Hm.", "Hungry.", "Big sky.", "Could lift that house. Won't.", "Good rock there. Good rock.", "Something small ran past. Fine.", "Walk. Walk is good."],
  ["I think I'm glowing a bit. Am I glowing?", "Look at the light! Just look!", "Everything's pretty if you squint. Squint!", "I'd like a hat with a jewel in it. Two jewels.", "Oh! A butterfly! Oh! Another!", "Shine on, everything.", "Twinkle. That's all I'm saying. Twinkle."],
  ["The hum changed.", "Something under us just turned over.", "I was elsewhere a moment ago. I'm back.", "Don't look at the shadows. They look back.", "I know what's under this field. I won't say.", "Cold. Always a bit cold. It's fine.", "They're nearly ready to come back. Not yet."],
];
/** Lines anyone might say, in no particular manner. */
export const SHARED_CHATTER: readonly string[] = ["Nice day for it.", "Long way from home.", "Did you hear that?", "Look.", "Hmm.", "What now?", "Whoa.", "Interesting.", "I don't like that.", "…", "Onwards."];
