/**
 * What Rises in the East: what the Mizukai Isles make, carry and fight.
 *
 * Mizukai steel is tamahagane, folded from the black iron sand of Kurohama's beaches and the charcoal of the Old Cedars:
 * katanas, the long nodachi, naginata, yari and tanto, the tall laminated bow. Armour is lacquered plates laced in
 * silk: the foot soldiers' (ashigaru) light kit, the samurai's full harness, and the green-laced harness of the fallen
 * Josaki clan, taken from its dead. Shrine people wear white and vermilion; the Bureau of Seals' sealwrights wear
 * indigo; the Mistwalkers, who carry messages nobody else should read, wear nothing anyone remembers.
 *
 * The creatures are the Isles' wayward spirits (spirit: true, so the Mizukai rites and wards answer them) and the
 * people and beasts who live among them. Every name is the Isles' own.
 */
import type { Bonuses, Drop, EquipSlot, IconShape, Item, MonsterDef, Skill } from "./data.ts";

export const MIZUKAI = { indigo: "#2f3a5e", ink: "#22252e", vermilion: "#b5452f", ivory: "#efe6d2", gold: "#c9a24a", crimson: "#8f2b2b", cedar: "#7a5a44", sakura: "#e8b4c0", steel: "#b9bec6", lacquer: "#1f1d22", jade: "#4f7a64" } as const;

type GearDef = { id: string; name: string; slot: EquipSlot; shape: IconShape; kind?: string; color: string; accent?: string; bonuses: Partial<Bonuses>; requires?: Partial<Record<Skill, number>>;
  value: number; weight?: number; speed?: number; two?: boolean; staff?: boolean; bow?: { range: number; strength?: number }; holy?: boolean; examine: string; ammo?: { strength: number; level: number }; tradeable?: boolean };
const gear = (def: GearDef): Item => ({
  id: def.id, name: def.name, examine: def.examine, value: def.value, weight: def.weight, icon: { shape: def.shape, color: def.color, accent: def.accent, kind: def.kind },
  ...(def.tradeable === false ? { tradeable: false } : {}), ...(def.ammo ? { stackable: true, ammo: def.ammo } : {}),
  ...(def.ammo ? {} : { equip: { slot: def.slot, bonuses: def.bonuses, requires: def.requires, ...(def.speed ? { speed: def.speed } : {}), ...(def.two ? { twoHanded: true } : {}), ...(def.staff ? { staff: true } : {}), ...(def.bow ? { bow: def.bow } : {}), ...(def.holy ? { holy: true } : {}) } }),
});
const g = (id: string, name: string, slot: EquipSlot, shape: IconShape, bonuses: Partial<Bonuses>, requires: Partial<Record<Skill, number>>, value: number, examine: string, extra: Partial<GearDef> = {}): GearDef =>
  ({ id, name, slot, shape, color: extra.color ?? MIZUKAI.steel, accent: extra.accent ?? MIZUKAI.lacquer, bonuses, requires, value, examine, ...extra });
const P = MIZUKAI;

export const MIZUKAI_GEAR: readonly GearDef[] = [
  // Blades: the katana in three grades, the clan swords, the long nodachi, the tanto; the polearms.
  g("kurohama_katana", "Kurohama katana", "weapon", "sword", { attack: 36, strength: 32 }, { attack: 40 }, 4200, "A harbour-forged katana: a curved, single-edged blade with a round iron guard and a grip wrapped in black cord. Light, quick, and sharper than it has any right to be.", { speed: 4, weight: 2, kind: "katana" }),
  g("tamahagane_katana", "Tamahagane katana", "weapon", "sword", { attack: 54, strength: 50 }, { attack: 60 }, 16000, "Folded tamahagane, the temper line running like a wave down the blade. The Ironsand Forge makes a few a season and argues about every one.", { speed: 4, weight: 2, kind: "katana", accent: P.gold }),
  g("takamori_katana", "Takamori katana", "weapon", "sword", { attack: 62, strength: 58 }, { attack: 70 }, 30000, "The lord of Takamori's gift: a blade from the clan's own forge, the crane crest on the guard, the scabbard lacquered indigo. Given, not sold.", { speed: 4, weight: 2, kind: "katana", accent: P.indigo, tradeable: false }),
  g("josaki_blade", "Josaki's Grief", "weapon", "sword", { attack: 66, strength: 64, prayer: 2 }, { attack: 75 }, 42000, "The last lord of Josaki's sword, the green silk of its grip gone grey. It is very calm in the hand, as if it has finished being angry.", { speed: 4, weight: 2, kind: "katana", accent: P.jade }),
  g("tamahagane_nodachi", "Tamahagane nodachi", "weapon", "greatsword", { attack: 68, strength: 76 }, { attack: 60, strength: 60 }, 24000, "A field sword taller than its bearer, carried on the back and drawn by someone else. Two hands, one cut, and usually enough.", { speed: 6, two: true, weight: 6, kind: "katana", accent: P.gold }),
  g("tanto", "Tanto", "weapon", "dagger", { attack: 32, strength: 26 }, { attack: 35 }, 2200, "A short blade for close quarters, its guard no wider than a coin.", { speed: 3, weight: 1, kind: "katana" }),
  g("naginata", "Naginata", "weapon", "spear", { attack: 56, strength: 60 }, { attack: 55 }, 14000, "A long curved blade on a lacquered pole: the shrine guards' weapon, and the castle women's. It keeps a horseman honest.", { speed: 5, two: true, weight: 5, kind: "glaive", accent: P.vermilion }),
  g("yari", "Yari", "weapon", "spear", { attack: 48, strength: 46 }, { attack: 45 }, 8000, "A straight spear with a flat, three-sided head. The foot soldiers' weapon, and the reason they win.", { speed: 5, two: true, weight: 4, accent: P.lacquer }),
  // Bows: the tall laminated yumi, gripped below the middle; the short half-bow; arrows with long fletching.
  g("mizukai_longbow", "Mizukai longbow", "weapon", "warbow", { ranged: 72 }, { ranged: 60 }, 15000, "A yumi of laminated bamboo and mulberry, taller than you, gripped a third of the way up. It is asymmetric on purpose and accurate by habit.", { speed: 5, two: true, bow: { range: 8, strength: 32 }, weight: 2, color: P.lacquer, accent: P.vermilion }),
  g("half_bow", "Mizukai half-bow", "weapon", "bow", { ranged: 46 }, { ranged: 40 }, 5200, "A short bamboo bow for the deck of a boat or the window of a castle.", { speed: 4, two: true, bow: { range: 7 }, weight: 1, color: "#8a6a3a", accent: P.lacquer }),
  g("mizukai_arrows", "Mizukai arrows", "weapon", "arrow", {}, {}, 50, "Cane-shafted arrows with long grey fletching and a broad, singing head.", { ammo: { strength: 42, level: 50 }, color: P.steel, accent: "#8f8f8f" }),
  // Magic and faith: the sealwright's brush-staff, the shrine wand and bell.
  g("sealwright_staff", "Sealwright's brush-staff", "weapon", "staff", { attack: 4, strength: 2, magic: 18 }, { magic: 55 }, 15000, "A staff with a great brush for a head, the bristles stiff with old ink. Sealwrights write their spells; this is the pen.", { speed: 5, staff: true, weight: 2, color: P.cedar, accent: P.ink }),
  g("shrine_wand", "Shrine wand", "weapon", "staff", { magic: 12, prayer: 6 }, { magic: 35, prayer: 30 }, 9000, "A wand of white wood hung with zigzag paper streamers. Waved over a thing, it is made clean. Holy.", { speed: 4, staff: true, weight: 1, kind: "wand", color: P.ivory, accent: P.ivory, holy: true }),
  g("shrine_bell", "Shrine bell", "shield", "scroll", { prayer: 8, magic: 4 }, { prayer: 40 }, 8600, "A cluster of little bells on a handle, rung in the shrine dances. Held in the off hand; spirits hear it a long way off.", { weight: 1, color: P.gold, accent: P.vermilion }),
  // Armour: the ashigaru's light kit.
  g("ashigaru_hat", "Ashigaru war-hat", "head", "hat", { defence: 14 }, { defence: 30 }, 1800, "A conical iron hat, lacquered black, worn by the lord's foot soldiers. Keeps off rain and the first arrow.", { weight: 1, kind: "kasa", color: P.lacquer, accent: P.gold }),
  g("ashigaru_do", "Ashigaru cuirass", "body", "body", { defence: 34 }, { defence: 30 }, 5200, "A plain lacquered breastplate, the lord's crest painted on the front. Issued, numbered, and collected back.", { weight: 4, kind: "plate", color: P.lacquer, accent: P.gold }),
  g("ashigaru_greaves", "Ashigaru greaves", "legs", "legs", { defence: 18 }, { defence: 30 }, 3000, "Lacquered splints laced over hakama.", { weight: 2, color: P.lacquer, accent: P.indigo }),
  // The samurai's harness: lacquered iron laced in indigo silk.
  g("samurai_kabuto", "Samurai kabuto", "head", "helm", { defence: 26, strength: 1 }, { defence: 60 }, 7200, "A lacquered helm with a broad neck-guard and two gilt horns rising from the brow. The face under it is somebody's; the helm is the clan's.", { weight: 2, kind: "kabuto", color: P.lacquer, accent: P.gold }),
  g("samurai_do", "Samurai cuirass", "body", "body", { defence: 64, strength: 2 }, { defence: 60 }, 18000, "Rows of lacquered iron scales laced with indigo silk, light for what it stops. Takes an hour to put on and a moment to be glad of.", { weight: 6, kind: "plate", color: P.lacquer, accent: P.indigo }),
  g("samurai_haidate", "Samurai haidate", "legs", "legs", { defence: 38 }, { defence: 60 }, 10000, "Thigh-guards of small plates sewn on cloth, laced in indigo.", { weight: 3, color: P.lacquer, accent: P.indigo }),
  g("samurai_kote", "Samurai kote", "hands", "gloves", { defence: 12, attack: 2 }, { defence: 60 }, 4200, "Armoured sleeves of mail and plate, laced to the shoulder.", { weight: 1, color: P.lacquer, accent: P.indigo }),
  g("samurai_suneate", "Samurai suneate", "feet", "boots", { defence: 12 }, { defence: 60 }, 4200, "Shin-guards over straw sandals: quiet on a floor, sure on a slope.", { weight: 1, color: P.lacquer, accent: P.indigo }),
  // Josaki's harness, laced in green: the fallen clan's, taken from its dead.
  g("josaki_kabuto", "Josaki kabuto", "head", "helm", { defence: 29, prayer: 1 }, { defence: 70 }, 12000, "A Josaki helm, green lacing, the crest a crescent moon. Someone has scratched a name inside the bowl.", { weight: 2, kind: "kabuto", color: "#2b3a32", accent: P.jade }),
  g("josaki_do", "Josaki cuirass", "body", "body", { defence: 70, prayer: 2 }, { defence: 70 }, 30000, "Green-laced plates gone grey at the edges, the lacquer cracked where a spear went in twenty years ago. Still good. Better than good.", { weight: 6, kind: "plate", color: "#2b3a32", accent: P.jade }),
  g("josaki_haidate", "Josaki haidate", "legs", "legs", { defence: 42, prayer: 1 }, { defence: 70 }, 17000, "Green-laced thigh-guards.", { weight: 3, color: "#2b3a32", accent: P.jade }),
  // Shrine people's white and vermilion; the sealwrights' indigo.
  g("shrine_hat", "Shrine hat", "head", "hat", { prayer: 3 }, {}, 900, "A tall black court hat of lacquered gauze, worn by priests at the altar.", { weight: 1, color: P.ink, accent: P.ivory }),
  g("shrine_robe", "Shrine robe", "body", "body", { prayer: 6, magic: 3, defence: 4 }, { prayer: 25 }, 3600, "White over vermilion, the sleeves wide enough to hold the whole morning's offerings.", { weight: 1, kind: "robe", color: P.ivory, accent: P.vermilion }),
  g("shrine_hakama", "Shrine hakama", "legs", "legs", { prayer: 3, defence: 2 }, { prayer: 25 }, 1800, "Vermilion divided skirts, pleated, worn by every shrine maiden and priest of the Isles.", { weight: 1, kind: "skirt", color: P.vermilion, accent: P.ivory }),
  g("sealwright_robe", "Sealwright's robe", "body", "body", { magic: 15, defence: 6 }, { magic: 50 }, 7600, "Indigo, ink-spotted to the elbow, a pocket for seals on each breast and one more nobody admits to.", { weight: 1, kind: "robe", color: P.indigo, accent: P.ivory }),
  g("sealwright_hood", "Sealwright's hood", "head", "hood", { magic: 6, defence: 4 }, { magic: 50 }, 3200, "An indigo hood with a paper seal pinned at the brow, in case.", { weight: 1, color: P.indigo, accent: P.ivory }),
  // The Mistwalkers': quiet, grey, forgettable on purpose. Each piece makes your hands lighter (Stealth).
  g("mistwalker_hood", "Mistwalker's hood", "head", "hood", { defence: 6, ranged: 3 }, { thieving: 40 }, 2400, "A grey hood that falls exactly where shadow does. A little easier to lift a purse in.", { weight: 1, color: "#5a5e66", accent: "#3b3f46" }),
  g("mistwalker_coat", "Mistwalker's coat", "body", "body", { defence: 14, ranged: 4 }, { thieving: 40 }, 4800, "A short grey coat with no buttons to catch the light and no pockets you could find.", { weight: 1, kind: "tunic", color: "#5a5e66", accent: "#3b3f46" }),
  g("mistwalker_trousers", "Mistwalker's trousers", "legs", "legs", { defence: 8 }, { thieving: 40 }, 2600, "Wrapped grey trousers, quiet in long grass.", { weight: 1, kind: "trousers", color: "#4a4e56", accent: "#3b3f46" }),
  // Charms, the war banner on the back, and the boatman's straw hat.
  g("paper_charm", "Paper charm", "neck", "amulet", { prayer: 2, defence: 2 }, {}, 600, "A folded paper charm in a brocade pouch. Wayward spirits strike it more softly (a little less damage from spirits).", { color: P.ivory, accent: P.vermilion }),
  g("fox_charm", "Fox charm", "neck", "amulet", { magic: 5, prayer: 2 }, { magic: 30 }, 5400, "A charm from Morishima's fox shrine: a key on one side, a jewel on the other. Spirits strike it more softly, and the foxes know you.", { color: P.gold, accent: P.vermilion }),
  g("turtle_charm", "Turtle charm", "neck", "amulet", { defence: 5, prayer: 1 }, {}, 3000, "A little stone turtle on a cord, from the wish shrine on Turtle Rock. Slow and certain. Spirits strike it more softly.", { color: "#7d8a7a", accent: P.gold }),
  g("takamori_banner", "Takamori sashimono", "cape", "cape", { defence: 3, strength: 3 }, { attack: 40 }, 6000, "A tall war banner worn on the back: the white crane of Takamori on indigo. So your side knows you in the smoke.", { weight: 1, kind: "takamori", color: P.indigo, accent: P.ivory }),
  g("straw_kasa", "Straw kasa", "head", "hat", { defence: 1 }, {}, 120, "A wide conical hat of woven straw. Rain, sun, and the curiosity of strangers run off it.", { weight: 1, kind: "kasa", color: "#c9b27a", accent: "#8a6a3a" }),
];

/** The Mizukai gear as items. */
export const mizukaiGear = (): Item[] => MIZUKAI_GEAR.map(gear);
const coins = (min: number, max: number, chance: number): Drop => ({ item: "coins", min, max, chance });
const one = (id: string, chance: number, min = 1, max = min): Drop => ({ item: id, min, max, chance });
const item = (id: string, name: string, examine: string, value: number, shape: IconShape, color: string, accent?: string, extra: Partial<Item> = {}): Item => ({ id, name, examine, value, icon: { shape, color, accent }, ...extra });

/** Everything else the Isles have: wood, iron sand, food and drink, paper seals, keys, and the quests' things. */
export const MIZUKAI_ITEMS: readonly Item[] = [
  item("bamboo_canes", "Bamboo canes", "Green canes, hollow and jointed. They burn fast and fletch light.", 40, "log", "#8fb36a", "#5f7a3a"),
  item("blossom_logs", "Blossom logs", "Wood from a blossom tree, pink at the heart. It burns sweet.", 160, "log", "#b07a6a", "#e8b4c0"),
  item("cedar_logs", "Cedar logs", "Red cedar from the Old Cedars, straight-grained and fragrant. Shrines are built of it, and nothing else.", 420, "log", "#8a4f36", "#c98a5a"),
  item("iron_sand", "Iron sand", "Black sand from Kurohama's beaches, heavy with iron. Smelted with charcoal, it becomes tamahagane.", 60, "ore", "#3b3a40", "#8f8f96", { stackable: true }),
  item("tamahagane_bar", "Tamahagane", "A bloom of Mizukai steel, folded and hammered: hard at the edge, soft at the spine, if the smith is good.", 1400, "bar", "#7d8590", "#c9a24a"),
  item("paper_seal", "Paper seal", "A strip of paper inked with a seal: the Isles' sigil. Mizukai spells and rites spend them.", 30, "sigil", "#efe6d2", "#b5452f", { stackable: true }),
  item("spirit_seal", "Spirit seal", "A seal written in the shrine's red ink on mulberry paper, folded twice. For the stronger rites.", 90, "sigil", "#e8d8b8", "#8f2b2b", { stackable: true }),
  item("rice", "Rice", "Short-grained Tanabe rice. Cook it on a range.", 6, "wheat", "#efe9dc", "#c9b27a"),
  item("rice_ball", "Rice ball", "Rice pressed round a salted plum, wrapped in seaweed. Heals 10.", 30, "bread", "#efe9dc", "#2f3a2e", { heal: 10 }),
  item("grilled_eel", "Grilled eel", "Eel glazed and grilled over charcoal. Heals 16.", 70, "fish", "#8a5a3a", "#c98a3a", { heal: 16 }),
  item("miso_soup", "Miso soup", "A bowl of miso with tofu and spring onion. Heals 8 and restores 20 run energy.", 40, "pot", "#c9a46a", "#5f7a3a", { heal: 8, energy: 20 }),
  item("sakura_mochi", "Blossom cake", "A rice cake wrapped in a salted blossom leaf. Heals 6 and raises Faith by 2 for a while.", 60, "cake", "#e8b4c0", "#5f7a3a", { heal: 6, food: { prayer: 2 } }),
  item("green_tea", "Green tea", "Kibi tea in a bowl. Heals 4 and raises Magic by 2 for a while.", 30, "mug", "#8fb36a", "#efe6d2", { heal: 4, drink: true, food: { magic: 2 } }),
  item("rice_wine", "Rice wine", "Warm rice wine in a small cup. Heals 6, raises Strength by 2 for a while, and makes the boat ride shorter.", 50, "bottle", "#efe9dc", "#c9a24a", { heal: 6, drink: true, food: { strength: 2 } }),
  item("cucumber", "Cucumber", "A fresh cucumber. River imps are said to love them more than anything. Heals 3.", 12, "berries", "#5f8a3a", "#c9d9a6", { heal: 3 }),
  // Keys: each dungeon's deepest door.
  item("kumo_seal_key", "Kumo seal-key", "A paper seal folded into the shape of a key. The Hollow's last door will accept it once.", 0, "key", "#efe6d2", "#b5452f", { stackable: true }),
  item("ogre_key", "Red iron key", "A key as long as your forearm, red with heat that never leaves it.", 0, "key", "#a5443a", "#3b3a40", { stackable: true }),
  item("bone_shrine_key", "Rib key", "A key carved from a rib. It is warm. You'd rather not think about whose.", 0, "key", "#efe9dc", "#8f8f8f", { stackable: true }),
  // Trophies and materials the yokai leave.
  item("spirit_silk", "Spirit silk", "Silk spun by a silk widow: grey, strong, and faintly cold. Tailors on Kurohama pay well for it.", 260, "silk", "#d8d8e0", "#8f8fa0", { stackable: true }),
  item("ogre_horn", "Ogre horn", "A horn from an ash ogre, still warm at the root. Takamori pays a bounty on every one.", 180, "trophy", "#8a3a2a", "#e8d8b8", { stackable: true }),
  item("fox_fire", "Foxfire", "A cold green flame in a paper lantern that never burns down. It wants to go home.", 120, "lamp", "#8fe0a8", "#efe6d2", { stackable: true }),
  item("crow_feather", "Crow-hermit's feather", "A black feather as long as your arm, its edge sharp enough to cut paper.", 90, "feather", "#2a2a32", "#5a5e66", { stackable: true }),
  // The quests' things.
  item("harbour_letter", "Harbourmaster's letter", "A letter of introduction from Harbourmaster Kaneda to the Hall of Takamori, sealed with the harbour's anchor.", 0, "scroll", "#efe6d2", "#2f3a5e", { tradeable: false }),
  item("sacred_rope", "Sacred rope", "A length of new rice-straw rope, twisted left, with paper zigzags tied in. The shrine's to give, not yours to keep.", 0, "string", "#c9b27a", "#efe6d2", { tradeable: false }),
  item("rice_straw", "Rice straw", "A bundle of last year's best straw from Tanabe, for the shrine's new rope.", 0, "wheat", "#c9b27a", "#8a6a3a", { tradeable: false }),
  // The Hidden Road (hiddenroad.ts): a lost walker's mask, for Ascetic Kōdō to burn.
  item("hermits_crow_mask", "Hermit's crow mask", "A crow's face of lacquered paper, beak cracked. Whoever wore it walked the Hidden Road and lost it, and the mask kept them lost.", 0, "hat", "#22252e", "#b9bec6", { tradeable: false }),
  item("binding_seal", "Binding seal", "A seal written by Sealwright Ren to tie into the shrine's rope. Don't read it; it doesn't like being read.", 0, "sigil", "#efe6d2", "#2f3a5e", { tradeable: false }),
  item("blank_seal", "Blank seal paper", "Mulberry paper cut to a seal's length, waiting for the ink.", 0, "scroll", "#efe6d2", "#c9b27a", { tradeable: false }),
  item("sealing_ink", "Sealing ink", "Ink ground with cedar ash and spring water from Kumoyama. Seals written in it hold.", 0, "vial", "#22252e", "#b5452f", { tradeable: false }),
  item("josaki_treaty", "The Josaki treaty", "Two copies of a treaty, one in each clan's hand. Both signed. One burnt at the edge. It says something neither clan admits it says.", 0, "scroll", "#e8d8b8", "#4f7a64", { tradeable: false }),
  item("lantern_name", "A name for a lantern", "A strip of paper with a drowned sailor's name on it, written by the Lantern Keeper.", 0, "scroll", "#efe6d2", "#c9a24a", { tradeable: false, stackable: true }),
  item("smugglers_ledger", "Smugglers' ledger", "The cove's accounts. Every crate, every boat, and the name of the person on Kurohama who's been paid to look away.", 0, "scroll", "#8a6a3a", "#2a2a32", { tradeable: false }),
  item("tea_tin", "First-flush tin", "A cedar tin of the year's first tea, sealed. For the Hall of Takamori.", 0, "pot", "#7a5a44", "#8fb36a", { tradeable: false }),
  item("blossom_poem", "The last blossom poem", "A poem on blossom-pink paper, finished at last. Three lines. You read it twice.", 0, "scroll", "#e8b4c0", "#2a2a32", { tradeable: false }),
  item("monkey_pass", "Bath-house pass", "A wooden pass for the Steaming Moon's bath, chewed at one corner.", 0, "tablet", "#c9a46a", "#7a5a44", { tradeable: false }),
  item("fox_key", "Fox's key", "A tiny brass key a fox dropped at your feet and then waited for you to pick up.", 0, "key", "#c9a24a", "#b5452f", { tradeable: false }),
  item("colossus_heart", "The Colossus's offering", "What the Starving Colossus had been holding all this time: the drowned's offerings, a bundle of names. The Lantern Keeper will know what to do.", 0, "trophy", "#efe9dc", "#c9a24a", { tradeable: false }),
];

/** The Isles' creatures: the wild, the wayward spirits (spirit: true), the Josaki dead, the ogres, the smugglers, the great ones. */
export const MIZUKAI_MONSTERS: Record<string, MonsterDef> = {
  snow_monkey: { id: "snow_monkey", name: "Snow monkey", level: 5, hp: 10, attack: 4, strength: 4, defence: 4, attackBonus: 0, defenceBonus: 0, maxHit: 1, speed: 4, respawn: 25, wander: 5, art: 200, ink: "#8a7a6a",
    examine: "A red-faced monkey with frost on its eyebrows. It has never paid for a bath.", always: [one("bones", 1)], drops: [coins(2, 20, 0.4), one("monkey_pass", 0), one("cucumber", 0.1)].filter(d => d.chance > 0) },
  parasol_imp: { id: "parasol_imp", spirit: true, name: "Hopping parasol", level: 6, hp: 12, attack: 5, strength: 4, defence: 6, attackBonus: 0, defenceBonus: 2, maxHit: 1, speed: 4, respawn: 25, wander: 6, weakness: "fire", art: 201, ink: "#a5443a",
    examine: "An old paper parasol that has grown one eye, one leg and a tongue. It wants to be used again. It isn't sure for what.", always: [], drops: [coins(3, 30, 0.5), one("paper_seal", 0.4, 2, 6), one("blank_seal", 0)].filter(d => d.chance > 0) },
  bellydrum_badger: { id: "bellydrum_badger", spirit: true, name: "Bellydrum badger", level: 12, hp: 20, attack: 9, strength: 10, defence: 9, attackBonus: 2, defenceBonus: 4, maxHit: 2, speed: 5, respawn: 30, wander: 5, art: 202, ink: "#6a5a4a",
    examine: "A round badger-dog with a leaf on its head and a belly it drums at the moon. It can look like a teapot, a monk or a stone, and gets bored halfway.", always: [one("bones", 1)], drops: [coins(10, 60, 0.6), one("sakura_mochi", 0.06), one("paper_seal", 0.2, 2, 5)] },
  serow: { id: "serow", name: "Mountain serow", level: 14, hp: 24, attack: 10, strength: 12, defence: 10, attackBonus: 2, defenceBonus: 4, maxHit: 3, speed: 4, respawn: 30, wander: 6, art: 203, ink: "#5a5a5e",
    examine: "A shaggy goat-antelope standing on a ledge that shouldn't hold it. It looks at you as if you're the strange one.", always: [one("bones", 1)], drops: [one("raw_beef", 0.8), one("cowhide", 0.3)] },
  river_imp: { id: "river_imp", spirit: true, name: "River imp", level: 18, hp: 28, attack: 14, strength: 14, defence: 12, attackBonus: 6, defenceBonus: 8, maxHit: 3, speed: 4, respawn: 30, wander: 5, aggressive: true, weakness: "wind", art: 204, ink: "#4f7a64",
    examine: "A green, beaked, child-sized thing with a dish of water on its head. If it spills, it weakens; if you bow, it bows back.", always: [one("bones", 1)], drops: [coins(12, 60, 0.6), one("cucumber", 0.2), one("raw_carp", 0.2), one("paper_seal", 0.2, 2, 6), one("clean_shiso", 0.08)] },
  mountain_boar: { id: "mountain_boar", name: "Cedar boar", level: 20, hp: 34, attack: 16, strength: 18, defence: 14, attackBonus: 6, defenceBonus: 8, maxHit: 4, speed: 4, respawn: 30, wander: 6, art: 118, ink: "#5a4a3a",
    examine: "A bristled boar the colour of cedar bark, with tusks it sharpens on shrines.", always: [one("bones", 1)], drops: [one("raw_beef", 0.9), one("cowhide", 0.2), coins(4, 30, 0.3)] },
  tree_whisper: { id: "tree_whisper", spirit: true, name: "Cedar whisperer", level: 24, hp: 36, attack: 18, strength: 16, defence: 20, magicDef: 16, attackBonus: 8, defenceBonus: 12, maxHit: 4, speed: 5, respawn: 35, wander: 3, weakness: "fire", attackStyle: "magic", art: 206, ink: "#9aab92",
    examine: "A small pale figure with a round head that clicks when it turns. The Old Cedars' own echo. It means no harm until you cut its tree.", always: [], drops: [coins(10, 80, 0.5), one("cedar_logs", 0.1), one("paper_seal", 0.3, 3, 8), one("clean_moon_mugwort", 0.06)] },
  lantern_wight: { id: "lantern_wight", spirit: true, undead: true, poisonImmune: true, name: "Lantern-wight", level: 30, hp: 40, attack: 22, strength: 18, defence: 22, magicDef: 24, attackBonus: 10, defenceBonus: 14, maxHit: 5, speed: 5, respawn: 35, wander: 4, aggressive: true, weakness: "water", attackStyle: "magic", art: 207, ink: "#c9a24a",
    examine: "A paper lantern split down one side into a mouth, a long tongue lolling out. It was lit for someone. Nobody came.", always: [one("bones", 1)], drops: [coins(14, 90, 0.6), one("paper_seal", 0.4, 3, 8), one("spirit_seal", 0.08, 1, 2), one("fox_fire", 0.05), one("kumo_seal_key", 0.02)] },
  foxfire_vixen: { id: "foxfire_vixen", spirit: true, name: "Foxfire vixen", level: 36, hp: 46, attack: 30, strength: 24, defence: 26, magicDef: 30, attackBonus: 18, defenceBonus: 18, maxHit: 6, speed: 4, respawn: 40, wander: 6, weakness: "holy", attackStyle: "magic", heals: 4, art: 208, ink: "#d98a3a",
    examine: "A fox with a green flame floating at each shoulder. It is not trying to fool you; it is trying to see if you can be fooled.", always: [one("bones", 1)], drops: [coins(20, 120, 0.6), one("fox_fire", 0.25), one("spirit_seal", 0.12, 1, 3), one("fox_charm", 0.005), one("clean_spirit_bell", 0.03)] },
  crow_hermit: { id: "crow_hermit", spirit: true, name: "Crow-masked hermit", level: 44, hp: 56, attack: 36, strength: 30, defence: 32, magicDef: 24, attackBonus: 22, defenceBonus: 20, maxHit: 7, speed: 4, respawn: 45, wander: 5, aggressive: true, weakness: "fire", ranged: 5, art: 209, ink: "#2a2a32",
    examine: "A long-nosed, black-winged hermit of the high slopes in a mask that may not be a mask. It throws wind like a stone and teaches swordsmen who ask the right way.", always: [one("bones", 1)], drops: [coins(30, 160, 0.6), one("crow_feather", 0.3), one("spirit_seal", 0.15, 1, 3), one("paper_seal", 0.3, 4, 10), one("kumo_seal_key", 0.03)] },
  grudge_wraith: { id: "grudge_wraith", spirit: true, undead: true, poisonImmune: true, name: "Grudge wraith", level: 48, hp: 58, attack: 40, strength: 34, defence: 30, magicDef: 40, attackBonus: 26, defenceBonus: 22, maxHit: 8, speed: 4, respawn: 45, wander: 4, aggressive: true, weakness: "holy", attackStyle: "magic", drain: { faith: 2 }, art: 210, ink: "#cfd2d8",
    examine: "Long black hair over a white face, white robes, no feet. A grudge that outlived the person who held it. It does not want you; it wants someone, and you're here.", always: [one("bones", 1)], drops: [coins(30, 180, 0.6), one("spirit_seal", 0.25, 1, 3), one("shade_sigil", 0.3, 4, 12), one("kumo_seal_key", 0.04)] },
  josaki_ronin: { id: "josaki_ronin", name: "Josaki ronin", level: 46, hp: 60, attack: 42, strength: 40, defence: 34, attackBonus: 30, defenceBonus: 26, maxHit: 8, speed: 4, respawn: 45, wander: 3, aggressive: true, faction: "josaki", art: 211, ink: "#2b3a32",
    examine: "A masterless swordsman in green-laced armour gone grey. The Josaki clan fell twenty years ago. Nobody told him; nobody could.", always: [one("bones", 1)], drops: [coins(40, 220, 0.7), one("kurohama_katana", 0.02), one("tanto", 0.03), one("rice_ball", 0.2), one("josaki_haidate", 0.002)] },
  josaki_retainer: { id: "josaki_retainer", spirit: true, undead: true, poisonImmune: true, name: "Ghost of a Josaki retainer", level: 58, hp: 70, attack: 52, strength: 50, defence: 44, magicDef: 30, attackBonus: 34, defenceBonus: 32, maxHit: 9, speed: 4, respawn: 50, wander: 3, aggressive: true, weakness: "holy", art: 212, ink: "#7fa892",
    examine: "A samurai who died on the walls, still guarding them. You can see the wall through him.", always: [one("bones", 1)], drops: [coins(50, 260, 0.7), one("spirit_seal", 0.2, 2, 4), one("josaki_kabuto", 0.003), one("josaki_haidate", 0.003), one("bone_shrine_key", 0.02)] },
  lord_josaki: { id: "lord_josaki", spirit: true, undead: true, poisonImmune: true, boss: true, name: "The Shade of Lord Josaki", level: 88, hp: 210, attack: 78, strength: 76, defence: 66, magicDef: 50, attackBonus: 56, defenceBonus: 50, maxHit: 15, speed: 4, respawn: 150, wander: 2, aggressive: true, enrage: true, weakness: "holy", size: 2, art: 213, ink: "#4f7a64",
    examine: "The last lord of Josaki, in his green-laced harness, his sword drawn. He has been waiting twenty years for someone from Takamori to come and say it plainly.", always: [coins(400, 1400, 1), one("bones", 1)], drops: [one("josaki_blade", 0.05), one("josaki_do", 0.04), one("josaki_kabuto", 0.05), one("josaki_haidate", 0.05), one("spirit_seal", 0.6, 4, 10), one("bone_shrine_key", 0.15)] },
  ash_ogre: { id: "ash_ogre", name: "Ash ogre", level: 60, hp: 88, attack: 54, strength: 60, defence: 46, attackBonus: 34, defenceBonus: 30, maxHit: 11, speed: 5, respawn: 50, wander: 4, aggressive: true, weakness: "water", art: 214, ink: "#7a4a3a",
    examine: "Twice your height, grey with ash, two horns and an iron club. It came up with the island's fire and decided to stay.", always: [one("bones", 1), one("ogre_horn", 1)], drops: [coins(60, 300, 0.7), one("blackiron_ore", 0.3, 2, 5), one("inkcoal", 0.3, 2, 5), one("iron_sand", 0.3, 5, 12), one("ogre_key", 0.04)] },
  red_ogre: { id: "red_ogre", boss: true, name: "Akagane, the Red Ogre", level: 96, hp: 260, attack: 84, strength: 90, defence: 70, attackBonus: 60, defenceBonus: 54, maxHit: 18, speed: 5, respawn: 160, wander: 2, aggressive: true, enrage: true, heals: 10, weakness: "water", size: 2, art: 214, ink: "#b5452f",
    examine: "The Red Ogre of Ashigane: the copper mine's fire in a body, a club of red iron, and a grudge against the whole of Takamori for something the first lord did.", always: [coins(500, 1800, 1), one("ogre_horn", 1, 3, 3)], drops: [one("tamahagane_bar", 0.5, 1, 3), one("tamahagane_nodachi", 0.04), one("samurai_do", 0.03), one("samurai_kabuto", 0.05), one("rough_rosestone", 0.2), one("ogre_key", 0.3)] },
  cove_smuggler: { id: "cove_smuggler", name: "Cove smuggler", level: 26, hp: 38, attack: 22, strength: 20, defence: 18, attackBonus: 12, defenceBonus: 10, maxHit: 5, speed: 4, respawn: 35, wander: 3, aggressive: true, art: 215, ink: "#3b3a40",
    examine: "A smuggler in a dark jacket with a knife and an excellent reason for being here that they'll tell you after you leave.", always: [one("bones", 1)], drops: [coins(30, 180, 0.8), one("rice_wine", 0.2), one("tanto", 0.02), one("mistwalker_hood", 0.004), one("half_bow", 0.01)] },
  sea_monk: { id: "sea_monk", spirit: true, name: "Sea monk", level: 70, hp: 96, attack: 62, strength: 58, defence: 50, magicDef: 44, attackBonus: 40, defenceBonus: 36, maxHit: 11, speed: 5, respawn: 60, wander: 3, aggressive: true, weakness: "wind", drain: { energy: 6 }, size: 2, art: 216, ink: "#1f2a3a",
    examine: "A great black shape risen out of the shallows: round-headed, smooth, eyes like two lamps. It asks for a bucket. Do not give it one with a bottom.", always: [one("bones", 1)], drops: [coins(80, 400, 0.7), one("raw_sailfish", 0.3, 1, 2), one("spirit_seal", 0.3, 2, 5), one("rough_moonstone", 0.05), one("tide_sigil", 0.4, 10, 25)] },
  silk_widow: { id: "silk_widow", spirit: true, name: "Silk widow", level: 52, hp: 64, attack: 44, strength: 40, defence: 38, magicDef: 30, attackBonus: 28, defenceBonus: 26, maxHit: 9, speed: 4, respawn: 45, wander: 4, aggressive: true, weakness: "fire", poison: { damage: 4, chance: 0.25 }, art: 217, ink: "#3a3448",
    examine: "A woman at a loom in the dark, until she turns round and has too many arms for a loom. Her silk is cold, fine and very strong.", always: [one("bones", 1)], drops: [coins(40, 220, 0.6), one("spirit_silk", 0.4, 1, 3), one("spirit_seal", 0.15, 1, 3), one("clean_spirit_bell", 0.04)] },
  starved_dead: { id: "starved_dead", spirit: true, undead: true, poisonImmune: true, name: "Starved dead", level: 64, hp: 80, attack: 56, strength: 54, defence: 46, magicDef: 30, attackBonus: 36, defenceBonus: 34, maxHit: 10, speed: 4, respawn: 50, wander: 4, aggressive: true, weakness: "holy", art: 218, ink: "#d9d4c4",
    examine: "Bones held together by hunger. The sea gave them back and nobody fed them.", always: [one("bones", 1)], drops: [coins(50, 260, 0.6), one("spirit_seal", 0.25, 2, 4), one("bone_shrine_key", 0.04), one("large_bones", 0.3)] },
  nightcall_chimera: { id: "nightcall_chimera", spirit: true, boss: true, name: "The Nightcall Chimera", level: 82, hp: 190, attack: 72, strength: 70, defence: 60, magicDef: 46, attackBonus: 50, defenceBonus: 44, maxHit: 14, speed: 4, respawn: 140, wander: 3, aggressive: true, enrage: true, weakness: "holy", poison: { damage: 5, chance: 0.2 }, size: 2, art: 219, ink: "#3a2f3a",
    examine: "A monkey's face, a badger's body, a tiger's legs and a snake for a tail, and a cry like a thrush in the dark that makes the lord's foresters stay home.", always: [coins(400, 1200, 1)], drops: [one("spirit_seal", 0.8, 4, 10), one("fox_charm", 0.04), one("crow_feather", 0.5, 2, 5), one("rough_moonstone", 0.2), one("insight_lamp", 0.03)] },
  hollow_seal_breaker: { id: "hollow_seal_breaker", spirit: true, boss: true, name: "The Seal-Breaker", level: 74, hp: 170, attack: 64, strength: 62, defence: 56, magicDef: 56, attackBonus: 46, defenceBonus: 40, maxHit: 12, speed: 4, respawn: 140, wander: 2, aggressive: true, enrage: true, weakness: "holy", attackStyle: "magic", drain: { faith: 3 }, size: 2, art: 220, ink: "#5a3a5e",
    examine: "A tall robed thing with a face of torn paper seals. It was sealed under Kumo a thousand years ago and has been reading the seals ever since, and found a mistake.", always: [coins(300, 1000, 1)], drops: [one("spirit_seal", 1, 6, 14), one("sealwright_staff", 0.04), one("sealwright_robe", 0.05), one("shrine_wand", 0.05), one("kumo_seal_key", 0.2)] },
  starving_colossus: { id: "starving_colossus", spirit: true, undead: true, poisonImmune: true, boss: true, name: "The Starving Colossus", level: 128, hp: 420, attack: 104, strength: 108, defence: 86, magicDef: 70, attackBonus: 76, defenceBonus: 68, maxHit: 24, speed: 5, respawn: 220, wander: 2, aggressive: true, enrage: true, weakness: "holy", drain: { faith: 4 }, size: 3, art: 221, ink: "#efe9dc",
    examine: "A skeleton as tall as a castle, made of everyone the sea took and nobody mourned. It is not angry. It is hungry. It has been hungry for a very long time.", always: [coins(1500, 5000, 1), one("large_bones", 1, 5, 5)], drops: [one("colossus_heart", 0), one("josaki_blade", 0.04), one("josaki_do", 0.04), one("takamori_banner", 0.05), one("spirit_seal", 1, 10, 25), one("insight_lamp", 0.08)].filter(d => d.chance > 0) },
};
