/**
 * What's new in the Realm, newest first. The game shows this log after an update (on the Updates tab of the daily
 * popup) until you've seen it. Add an entry with the next id for every update players should hear about.
 */
export type Update = { id: number; date: string; title: string; items: readonly string[] };
export const UPDATES: readonly Update[] = [
  { id: 48, date: "2026-10-05", title: "Work orders, your own daily challenges, and the quests of being known", items: [
    "Work orders: ten craftsfolk pay well over shop prices for what you can make at your level, one order each a day and yours alone: Hazel (bows), Brann (smithed arms), Cook Mabel (cooked food), Rowan (logs), the old fisher and Nell Gutting (fish), Mother Yarrow (potions), Bolt (leatherwork), Gristle (ore) and Scribe Nettle (sigils). Ask them \"Any work going?\": they ask for the best thing you can make, pay coins at half as much again as it's worth plus a fee that grows with your level, and give XP in the skill and a little Presence.",
    "Daily challenges are now rolled for you alone (from the day and your token), so no two players share a day's three. A new kind asks you to fill one or two work orders.",
    "Three long quests for Presence, each with gear nothing else gives: A Name Worth Knowing (Namekeeper Elian, Presence 20 and a name: the Wanderer's cloak, Presence a fifth faster), Known in Every Hall (Archivist Perrin, Presence 40: the Chronicler's mantle, work orders pay 15% more, and the Storyteller's hat), and The Remembered (King Hollis, Presence 60: the Blade of Renown, whose strength grows with your Presence, and the Cape of Renown, Presence a third faster).",
    "The Presence skill guide now lists what every level brings: titles, how townsfolk and your Friend treat you at 10, 20, 30, 40, 50 and 70, and the quest gear.",
    "Townsfolk look like people now: villagers in every town and village have people-shaped bodies in many builds (slim, stout, broad, round, tall, short, elders with a stick), each one different, with the parent-and-child look now rare.",
    "The adventurer card is yours to style: eight backgrounds, eight backdrops behind your Friend, four skills panels, four letterings, five inks and three layouts, unlocked by Presence, quests and achievements, chosen on the card screen and saved. It shows your name with the token id small beside it, your title, and your fellowship. A fellowship's founder can give it a logo and a header background: add preview/fellowships/<TAG>/logo.png and bg.png to the site (README there) and every member's card wears them.",
    "The ossuary bag can be worn on the back (the cape slot, +2 Faith): worn or carried it catches the bones you pick up, and praying at an altar while wearing it offers everything inside.",
    "Twelve new wardrobe pieces in the Rare Caskets: ember and ash scarves, sky and moss bows, plum, sea, snow and starfall capes, rose and dawn halos, ember and night wings, hollow wisps, a void aura and the Deadwood crown. The Realm Daily takes simulated RF too: reroll the day's challenges for a casket, or buy the day done for two (the caskets are yours to open as well).",
    "The adventurer card draws your Friend larger, drops the aura ring behind it, and every layout is free, with a new Poster layout. Colour pickers set your own ink, background and backdrop colours over any preset.",
    "Fellowships have their own menu (from the Presence profile): rename the fellowship for 2,500 coins (the tag stays), pick its emblem (twelve), its card banner (eight styles) and two colours. The banner and emblem show on the adventurer card with every background and layout; a drawn logo and banner in the site's fellowships folder take their place when present.",
    "The ember salamanders in the Ashen Hills mine by Friendhollow are young ones now (level 7, not aggressive): a beginner's foe for a beginner's mine. The cart-sized adults (level 70, the Cindershell set) keep to the deep mine under Cragmaw.",
    "The side panel folds: its tab buttons now sit along the bottom right. Press a tab to open it, press the open tab (or the arrow at the end) to fold the panel away and see the Realm; the hotkeys (I, K, L, P, N, O, F1 to F10) open it too.",
  ] },
  { id: 47, date: "2026-10-05", title: "Every tree falls, sigils with their marks, a Friend with a thousand things to say, and the Deadwood's dead", items: [
    "Every tree in the Realm can be cut and burnt. Palms (Woodcutting 25) on the Oasis, Southshore and Pale Isles; pines (35) on the Greyhorn, Frostpeak, Drakespine and Ironreach slopes; the dead trees of the Deadwood, Murkmire and Ashfall (55). Their logs burn for Firemaking, palm and pine logs fletch into bows (Fletching 40 and 52, Ranged 25 and 35), and a knife on deadwood logs cuts a Deadwood wand (Fletching 58): a one-handed magic weapon that autocasts like a staff, at Magic 50.",
    "Every sigil carries its own mark on the stone: a swirl for breeze, a wave for tide, a flame for ember, an eye for thought, a bolt for storm, a path's arrow, a flower for bloom, a star, a crescent for shade, a dark ring for hollow.",
    "The Deadwood is full of its dead: fourteen roofless ruined houses with what the people left behind (beds rotted to lace, a table laid for four), Ashworth Hall with its tomb under the floor, six named crypts with stories carved on the tombs inside (the Three Sisters, the Namekeeper's, one with the lid moved from the inside), railed family plots, tombs and obelisks, bone-heaps, and three kinds of headstone with epitaphs worth reading.",
    "Your Friend has a far bigger bank of things to say: every family has its own remarks for every skill you train (fishing, mining, cooking, thieving, offering bones), storms, fog, snow and lava underfoot, villages, ruins, a full pack, a shop, a bank, a level, your pet, and idle chatter drawn at random so no two Friends sound alike. Overhead text now sits above your name and tag instead of behind them.",
    "Presence takes longer: it is meant to be the slowest skill in the Realm, so all stray Presence XP is halved. The profile shows its progress bar. The Presence icon is an adventurer (hat, cape and staff) rather than a second Faith.",
    "The spellbook's tabs are the same dark brown as the graphics buttons; examining a spell lists the sigils and any quest it needs in the chat; the chat can be folded away with the arrow in its corner. Settings has a Nameplates choice (Full, Name only, Hidden) for what shows over players, and the save and restore buttons wear the same dark style.",
  ] },
  { id: 46, date: "2026-10-05", title: "A Friend that talks back, rumours in every village, and the Realm's history", items: [
    "Your Friend has a voice. Now and then it remarks on the world in its family's own manner: a Skeleton is dry (\"Finally. Someone who planned ahead.\" at a grave), a Colossus blunt (\"Big.\"), a Hoverer wants to know what's over the hill, a Hollow Friend hears things hum. It speaks to where you are, the weather, the hour, what's near, what you're doing, and what you've lived: first dragons, first deaths, old haunts. The line shows over its head and in chat as your name; on Full, players nearby hear it. Settings: Friend speech, Full, Reduced, Rare or Off.",
    "Rumours: ask townsfolk, traders and innkeepers what they've heard. Every settlement has its own, some true, some half-true, some nonsense, a few pointing at things nobody explains (a door under the lake, a village beyond the mountains that doesn't like Friends, King Hollis never leaving the castle). A new rumour is worth a little Presence. The game never says which are true.",
    "People notice you. Some NPCs greet your Friend's family the first time they meet it (a Skeleton at Dawnhold gets a look; a Colossus in Cragmaw, \"By the old stones\"). As your Presence grows they recognise you: \"Back already?\" at 20, your name at 40, \"Everyone here knows\" you at 70.",
    "Things that tell a story without saying it: a burned farmhouse in Westmarch with three beds and a child's wooden horse, footprints to the trees and nothing after; an altar used as a fence post in the Thistle Vale; ancient stonework under the Thistle road; a shrine deep in the Deadwood to a bearded figure whose face has been chiselled off, with a candle somebody keeps lit; a seized mechanism the size of a mill under Ironreach; a fisherman's shack on Southshore nobody has lived in for years; and watch-stones along the Westmarch road, every one toppled westward, from when Friendhollow's castle was built against something that came from the west.",
    "Fernwick has a history: Rowan will tell you how its children learn their trees before their letters, and Hazel, once her quest is done, about the first war bow and the one in the castle armoury that has never been drawn.",
    "Every weapon and piece of armour in the six ore metals can now be bought somewhere: the Ironreach Armoury in Cragmaw (Brenna Anvilsong) sells every glimmer and rarite piece, helms to greaves, daggers to war hammers; Gravesend's Last Lantern sells moonsilver plate salvaged from the Deadwood. Worth the walk.",
    "The website has a Lore page: the Realm's history, the Old Friend, the First Friends, the Hollow, and a card for every region (who lives there, what they believe, fear, trade and whisper). Deliberately incomplete.",
    "The spellbook has tabs: Combat, Curses, Utility and Teleports, each counting what you've learnt. Eleven new glides: to Fernwick, Highcairn, Dawnhold and every village of the wider world (Gravesend, Saltmarrow, Hollyhock, Dyemoor, Tallgrass, Cragmaw, Quillhaven) and to Ember Tamsin's camp at Ashfall. All but Highcairn are learnt by doing the place's own quest; the sigils are the easy part.",
  ] },
  { id: 45, date: "2026-10-05", title: "The Wider World: the mainland becomes the heart of a continent", items: [
    "The Realm is four times its size. The old mainland is exactly where it was (every town, road, dungeon and quest), and the world now runs out from it in every direction: the Deadwood to the north, Westmarch and the long Drakespine peninsula to the west with Ashfall, the dragons' country, at its far end, Southshore and the Thistle Vale to the south, the Ironreach mountains and The Wilds to the east, and the Pale Isles out at sea. The coast is bays, headlands and islands now, not a rectangle. Distance matters: the far villages are a real journey on long roads, mountain passes, bridges and a ferry.",
    "Seven new villages, each with its own trade, people, shops and a quest: Gravesend (the graveyard settlement at the Deadwood's edge), Saltmarrow (fishing, with a bank and the ferry to the Pale Isles), Hollyhock (the apothecary village, with a bank), Dyemoor (the dyers), Tallgrass (the hunters' camp), Cragmaw (the Ironreach mine, with a bank, furnace and anvil) and Quillhaven (the scholars' library). Ember Tamsin camps at the edge of Ashfall. Eight new quests, twenty in all.",
    "Regional clothing: every village sells its own (Gravesend's mourning charcoal and lantern purple, Saltmarrow's oilskins, Hollyhock's aprons and leaf-pinned capes, Dyemoor's indigo and madder, Tallgrass's grass greens and pelt capes, Cragmaw's fur hoods and greatcoats, Quillhaven's robes and caps, Ashfall's scorched leathers), and its people wear it. You can tell where a Friend has been by what it's wearing.",
    "Four new underground dungeons, each reached only by its surface entrance: the Deadwood Catacombs (stairs under the ruined chapel at the end of the old road), the Wyrm's Lair (the crater at Ashfall's far end), Saltmarrow's sea cave (a trapdoor in the abandoned hut on the north quay) and Cragmaw's deep mine (the shaft behind the camp). Nothing of them shows from above.",
    "Apothecary, a new skill: pick herbs (every ecosystem grows its own, forest, swamp, mountain, Deadwood, Ashfall, coast and desert, common to very rare), Clean them, grind some with a pestle and mortar, distil essences at the still in Hollyhock, and brew with a vial of water: healing and energy tonics, Attack, Strength, Defence, Ranged and Magic potions (boosts that wear off a point at a time), a Faith potion, an antidote, an antifire potion, a stealth draught, a Wayfarer's tonic, and three weapon poisons. Mother Yarrow in Hollyhock sells the vials and the first herbs.",
    "Poison matters: coat a melee weapon and each hit poisons soft-bodied creatures (boars, thornbacks, stalkers feel it half as much again); the undead and stone ignore all but wraith poison, which also saps their defence. Marsh adders in every bog and cave spiders in the dark places poison you back; an antidote cures it and keeps it off for five minutes.",
    "Friend mixtures: nine rare recipes, one for each Friend family, at Apothecary 80 to 90. Not stronger potions: something of that family's own nature for ten minutes (Skeletons' Marrow draught doubles Faith XP from bones, Hoverers' Updraught makes running free, Sparkling Friends' Glimmerwine gives +15% XP, the Hollow draught keeps sigils half the time, and so on). A mixture made for another family does nothing for yours.",
    "Presence, a new skill: the mark you leave on the world. Earned by discovering regions, finishing quests, felling bosses, rare finds, people met, emotes learnt, clothes worn for the first time, your name, your fellowship and time with your Friend behind you. It opens as a character profile (click Presence in the Skills tab): name, Friend, fellowship, title, style, favourite skill, home region, reputation with every settlement, achievements, emotes and wardrobe.",
    "Name your Friend: a new Friend is asked for a name on first entering the Realm, and Namekeeper Elian by the Friendhollow square renames for 1,000 coins. The token id never changes: it shows small and faded under the name. Chat and the adventurer card use the name.",
    "Fellowships: found or declare one from the Presence profile (5,000 coins): a name and a tag of up to five letters, shown between your name and your token id. Everyone online wearing the tag is your company. Fifteen titles to earn, by Presence level and by deed (Dragonfriend, Lanternkeeper, Sea-tithed, Knight-Paladin, Kingslayer…), shown when someone examines you.",
    "Twenty new music tracks, one for every new region and dungeon. The world map shows the whole continent (press Whole Realm). Five new achievements.",
  ] },
  { id: 44, date: "2026-10-04", title: "The Heartguard, Dawnhold Keep, and the Old Friend at every altar", items: [
    "The Heartguard: red-and-white armour earned with Hitpoints, sold by Mender Hale at the Friendhollow chapel. A piece every ten levels, from boots at 10 to the Heartguard blade at 90 (helm, greaves, shield, amulet, cape and plate between). Every piece worn adds a hitpoint and quickens your healing by 6%; wear all nine and food heals a quarter more. The blade heals you one for every eight damage it deals.",
    "Dawnhold has its fortress: Dawnhold Keep, a two-storey stone hold joining the chapel and the hall along their east ends, its gate facing straight down the causeway from Highcairn, with a round tower at each outer corner, a throne, banners and suits of Dawnplate inside. The chapel stands taller, in two storeys of white stone with a bell tower at its corner.",
    "Every altar in the Realm now has a statue of the Old Friend behind it: the bearded Friend the Realm prays to, carved in pale stone under a sun disc, in the Friendhollow chapel, the Dawnhold chapel, the Highcairn mountain shrine and the Murkmire crypt.",
    "A new achievement, Heart of the Realm, for owning the whole Heartguard. The Hitpoints skill guide lists every piece.",
  ] },
  { id: 43, date: "2026-10-04", title: "The Wayfaring update, and the Warden's creatures", items: [
    "Agility is now Wayfaring. Your levels and XP carry over, and so does everything Agility did: run energy comes back faster with every level.",
    "Wayfaring does more: running drains less energy the better you are (40% less at 99), and hard obstacles can be slipped on (a fifth of the time at their own level, never twelve levels above it; a slip hurts a little and breaks the lap).",
    "Two new courses: the Oasis dune course south-east of the Oasis (Wayfaring 30, six obstacles) and the Frostpeak ice course north of the camp (Wayfaring 55). The Friendhollow course is still where it was.",
    "Wayfarer's marks: every lap of a course pays marks (one, two or three by course). Coach Skip trades them for the Wayfarer's outfit: boots (run energy comes back half as fast again), gloves (you never slip), hood (+10% Wayfaring XP) and cape (running drains 20% less; the full outfit 40%, and double marks), and for waybread, a travellers' loaf that restores 40 run energy.",
    "Five new Slayer creatures only a Slayer can wound, each with its own task and its own armour: thornbacks in southern Whisperwood (Slayer 15, Bramble armour: thorns that hurt whatever hits you), cairn wights in the Greyhorn (35, Wightbone: more Faith XP from bones), dune stalkers in the northern dunes (45, Stalker's: harder to notice while sneaking, cheaper sneaking), ember salamanders in the Ashen Hills (60, Cindershell: dragonfire burns far less) and Hollow weavers in the Hollow Depths (75, Hollowthread robes: spells keep their sigils). Each piece does a little; the full set does more.",
    "Two new Warden rewards: the Warden's bracers (250 points, +10% Slayer XP on task) and Longer tasks (100 points: tasks and their points half as big again; switch it off for free).",
    "The Warden now picks your task from the six hardest you qualify for, whatever order they're listed in. The Skills guide lists every course, piece of Wayfarer's gear and Slayer set, and three new achievements: Wayfarer, Dressed for the road and The Warden's wardrobe.",
  ] },
  { id: 42, date: "2026-10-04", title: "Heavy weapons that take Strength, a better quest journal, and the ossuary bag", items: [
    "Greatswords, battleaxes and war hammers now take Strength to wield as well as Attack: pewter at Strength 3, 5 and 7, and each metal's own level more for every tier up (blackiron 7, 9 and 11; ashsteel 12, 14 and 16; and so on to ashenheart at 92, 94 and 96). One already in your hands stays there until you take it off.",
    "Heft: a two-handed weapon swings harder the stronger you are. Your Strength adds 1% of the weapon's strength bonus for every two levels (half as much again at 99). The Worn equipment tab shows what your heft adds, and the Strength skill guide lists every heavy weapon.",
    "The quest journal groups quests into In progress (orange), Not started (white) and Complete (green), with a quest point bar, each quest's difficulty and points, and a step count (2/3) beside quests you're on. Open one for its status, where to start it and its rewards; the Quest complete window lists the rewards too.",
    "Use bones on an altar and you keep offering them, one every couple of ticks, until your pack has none of that kind left. Walk away to stop.",
    "The ossuary bag, the Dawn Vigil's new reward: it holds 60 bones of any kind, bones you pick up go straight into it, and using it on an altar offers every bone inside at once (the chapel's three-times blessing included). Right-click it to Check, Fill or Empty, or use bones on it. Already kept the vigil? Sister Maren in the Dawnhold chapel has one for you.",
  ] },
  { id: 41, date: "2026-09-30", title: "Lanterns up high, and hills that hide what's behind them", items: [
    "Lanterns and chandeliers hang higher, up in the rafters, and one that would sit in front of your Friend's face turns see-through.",
    "Snowy slopes and hills cover whatever stands behind them: Friends, other players, monsters and houses no longer show through the snow around Highcairn (or any other hill).",
    "Friends standing beside Hollow Square's fountain no longer clip into its rim.",
  ] },
  { id: 40, date: "2026-09-30", title: "The Stealth update, lamplit rooms, mastery capes and a new fountain", items: [
    "Thieving is now Stealth. Your levels and XP carry over, and pickpocketing and the Oasis stalls are part of it.",
    "Sneak (the hooded button beside your run energy, or C): walk softly past aggressive monsters. Each tick they may notice you (their level against your Stealth, how close you are, whether you're moving). Slip out of reach unseen for Stealth XP. It spends run energy faster than running, less as your Stealth grows.",
    "Get spotted and the monster lunges at once: you take a hit, the sneak ends and the fight is on.",
    "Sneak attacks: strike a monster that hasn't noticed you and your first blow lands harder and truer.",
    "Light feet: from Stealth 50 aggressive monsters notice you from 3 tiles instead of 4, and from 80, only 2.",
    "The Veilweave hood: found very rarely in the shadows while slipping past monsters of level 38 and up (Stealth 60). Wear it from 70 and stand still for five seconds, and you fade almost to nothing; aggressive monsters look straight through you. Other players see you fade too.",
    "Two new achievements: Ghost in the grass and Now you see me.",
    "Every room in the Realm is lamplit: hanging lanterns in the houses and shops, iron chandeliers in the castle's halls, on every storey. Windows glow warm at night.",
    "Mastery capes stand out as capes of accomplishment: a yoke across the shoulders in the skill's second colour, a band above the hem, the skill's emblem on the back in a roundel, and gold edges on trimmed capes. The Grandmaster's carries a gold star.",
    "Hollow Square's fountain is rebuilt: a wide eight-sided stone basin of pixel water with wishing coins, a column and a bowl spilling over its lip, and a jet on top. It glows softly at night.",
    "Fixed: shared fights and dropped items in the Greyhorn Highlands (the far east) now work with other players.",
  ] },
  { id: 39, date: "2026-09-29", title: "Bank tabs fixed, and save codes that stay saved", items: [
    "Bank tabs no longer squash the bank: with several tabs the All items view lists each tab under its own heading and scrolls, and the shop's stock does the same.",
    "Restoring a save code saves it at once. Before, a second tab or window with the game open could quietly overwrite the restored adventure with its own.",
    "One tab saves at a time: when you open the Realm in a newer tab, the older one stops saving and tells you so (reload it to continue there).",
    "Settings says plainly when saves aren't connected, and the page keeps trying to connect them for about a minute instead of ten seconds.",
  ] },
  { id: 38, date: "2026-09-29", title: "Low graphics that look like High, and a roomier town", items: [
    "Low graphics now use High's textures and lighting: the same ground, walls and roofs, the same daylight, dusk and lamplight, and buildings still cast their shadows. Low leaves out the shadows of trees and Friends, the far haze and cloud shadows, and lays its light more coarsely, so it stays quick.",
    "Both settings draw faster: nothing off the screen is drawn, and the hidden sides of flat roofs and walls are skipped.",
    "The Sleepy Friend inn has moved across the east bridge, on its own with a cobbled step up to its door, and the house behind Fletch & Feather has moved back so its door isn't a tile from the next wall.",
  ] },
  { id: 37, date: "2026-09-29", title: "Real clothes, boots and gauntlets, and armour that fits", items: [
    "Ribbon & Rye Clothiers, west of the south end of Market Street: shirts in eight colours, belted tunics, dresses that sweep the floor, trousers and skirts. They're for looks (no combat bonuses), and the townsfolk wear them too.",
    "Boots and gauntlets in every metal, smithed at the anvil (one bar each) and sold beside the helms in the armouries. Dawnplate has them too: boots from The Pilgrim's Road, gauntlets from The Restless Crypt.",
    "Boots, gloves and gauntlets show on your Friend, along with the rest of your armour.",
    "Helms fit your Friend's head, following its outline, and four-legged Friends wear chest plates as barding over the back instead of shoulder plates up by the head.",
  ] },
  { id: 36, date: "2026-09-29", title: "Cleaner world: health bars in fights only, High by default, whole helms", items: [
    "Health bars only show while something is fighting: monsters when they're attacking you, you're attacking them, another player is fighting them or they've just been hit; yours and other players' in combat. (A monster's level is still in its right-click menu.)",
    "Graphics are High by default and never change by themselves; choose Low in Settings if you want it.",
    "Helms are one shell from every side: open at the face with a nose guard from the front, turned with you from the side, and closed with a ridge from behind.",
  ] },
  { id: 35, date: "2026-09-29", title: "Dressed-up townsfolk", items: [
    "Villagers wear their own hats (wizard's points, feathered caps, traveller's hats, hoods), some wear capes in every colour and pattern, a few an amulet, and some carry an axe or a pickaxe. Each keeps their look.",
    "Townsfolk dress for their trades: the old miner and the mountain guide carry pickaxes, Axel and the Fernwick foresters axes, the fisher and the miller wear straw hats, and Tamsin the tailor is the best dressed of all.",
    "More villagers about in Fernwick, the Frostpeak camp and Highcairn.",
  ] },
  { id: 34, date: "2026-09-29", title: "Dawnplate, three Order quests, armour you can see, and smoother graphics", items: [
    "Three new quests for the Order of the Dawn. The Pilgrim's Road (Sister Maren, Faith 35): pray at the Realm's three old altars. The Restless Crypt (Faith 45): lay twelve crypt skeletons to rest with a faith weapon. Dawn Against the Hollow (Grandmaster Aldric, Faith 60, after The Hollow King): destroy five Hollow sentinels with a faith weapon and bring three Hollow essence to seal their gate.",
    "Dawnplate, the Order's gold armour with white trim (Defence 70, Faith 60): greaves, helm and shield, and the cuirass for Dawn Against the Hollow. Each quest's pieces are sold in the Order Armoury once you've earned them.",
    "Armour shows on your Friend: cuirasses as breastplates with shoulder plates, vests and robes, and greaves on your legs. Helms are closed at the back now, and the castle guards and knights of the Dawn wear their armour too.",
    "Your settings are remembered in this browser. High and Low stay as you set them; only Auto adjusts itself, and on a slow high-DPI screen it first draws fewer pixels (keeping the lighting) before it tries Low.",
    "High draws at up to 1.5× on high-DPI screens (the pixel art looks the same, with about half the pixels of 2× to light), and the lighting's hidden passes skip the ink outlines, so laptops run it more smoothly. Cached art is kept least-recently-used, with less of it.",
  ] },
  { id: 33, date: "2026-09-29", title: "The Faith update: the Order of the Dawn", items: [
    "Prayer is now Faith. Your levels, XP and prayers carry over; faith is what your prayers draw on, and altars restore it.",
    "The Order of the Dawn keeps Dawnhold, a chapterhouse on a terrace above the sea east of Highcairn (a cobbled causeway runs there through the ridge): Grandmaster Aldric, Sister Maren the chaplain, Quartermaster Bram and the knights of the Dawn in white and gold.",
    "New quest, The Dawn Vigil (Novice, Faith 10): offer bones on the Dawnhold chapel altar and become a squire of the Order. Reward: a Dawnsteel sword, 1,500 Faith XP and the Order Armoury.",
    "New quest, Light in the Greyhorn (Intermediate, Faith 30): win the shards of the Order's broken relic back from the stone golems of the Greyhorn mine and bless them on the altar. Reward: the Cape of the Dawn, 5,000 Faith XP, 2,000 Defence XP and the Order's finest weapons.",
    "Faith weapons, which need Faith as well as Attack or Magic: the Dawnsteel sword, the Vigil spear, the Radiant greatsword and the Sunforged warhammer, and the Acolyte's staff, the Dawn staff and the Staff of the First Light. Every hit you land with one gives a little Faith XP, and they hurt the undead (skeletons, shades and the Hollow) harder.",
    "More ways to train Faith: use bones on any altar to offer them for twice the XP of burying, or three times on the Dawnhold chapel altar.",
  ] },
  { id: 32, date: "2026-09-29", title: "Capes, hats and amulets, and sharper guards", items: [
    "Threadneedle Tailors on Market Street, across from Heft & Haft: capes in ten solid colours and seven patterns (stripes, halves, a chevron, quarters, a gold border, stars and a pilgrim's cross), wizard hats in six colours, feathered caps and wide-brimmed traveller's hats.",
    "Amulets and pendants show on your Friend now (and on other players), hanging round the neck.",
    "Seen from behind, your weapon or tool is held beside your cape instead of cutting across it.",
    "The castle guards wear helms and red capes and carry battleaxes; Captain Rook carries a greatsword.",
    "Snowy peaks no longer vanish when you turn the camera (the land is drawn back to front at every angle), and the distance haze follows the land, so nearby mountains are never hazed.",
  ] },
  { id: 31, date: "2026-09-29", title: "New lighting: real shadows, sunlight and lamplight", items: [
    "The sun moves across the sky: it rises in the east, crosses the south and sets in the west. Buildings, walls, trees, rocks, characters and mounts cast shadows that follow it, long and golden at dawn and dusk, short at noon, and faint in the moonlight.",
    "Lamps, torches, fires, forges and spells light the ground and everything standing near them instead of glowing over it, and walls, rocks and trees block their light.",
    "Light bounces: a fire's glow spills softly round corners in the colour of the ground, lava lights up everything around it, and dungeons are truly dark away from the flames.",
    "Softer ambient light: corners, alleys, forest floors and the spaces under roofs are darker, and the sky's colour changes through the day. At night the haze and fog turn a dim blue.",
    "On Low graphics a clear day is drawn as before, and nights stay lit, without the shadows.",
  ] },
  { id: 30, date: "2026-09-29", title: "Two-handed weapons, new creatures and sharper skill icons", items: [
    "Two-handed greatswords, battleaxes and war hammers in every metal: a tick slower than a sword and much harder hitting, with no room for a shield. Smith them at an anvil (3 bars), or buy them at Heft & Haft, the new shop at the south end of Market Street.",
    "New creatures: forest spiders in Whisperwood, wild boars in the southern woods, sand scorpions in the Pale Dunes, highland goats on the Greyhorn slopes and stone golems in the Greyhorn mine.",
    "Each has something only it drops: a spider-fang dagger, a two-handed Tusker axe, a Horned helm, a Stinger sabre and a Golem maul. Grumblins now carry the odd Grumblin spear, and moss colossi a Mossy staff or a Mossblade.",
    "The skill icons are redrawn, crisp and shaded like the items and tabs.",
    "Arrow shafts give 8 Fletching XP (up from 5).",
  ] },
  { id: 29, date: "2026-09-29", title: "Highcairn, the Greyhorn Highlands, sheep and string", items: [
    "The Realm is bigger: east of the Pale Dunes and south of Frostpeak the island swells into the Greyhorn Highlands, with a ragged new coast. Snowy peaks, scree slopes and crags, all walkable, a mountain lake, and the Greyhorn mine (glimmer, rarite and moonsilver).",
    "Highcairn, a stone town on a plateau in the middle: a bank, the Highcairn Stores, the Stone Kettle inn, the Highcairn Forge, a mountain shrine and a Rare Market trader. Roads climb to it from the Frostpeak camp and the Oasis.",
    "Sheep! A new pen between the cows and the chickens. Shear them with shears (any general store) for wool; a shorn sheep looks shorn until its fleece grows back.",
    "Spin wool into string at a spinning wheel (the farmhouse, or Tessa's tannery in Friendhollow): Crafting level 1.",
    "Bows need strings now: a knife on logs cuts an unstrung bow (or war bow), and a string finishes it. A string on a cut gem makes an amulet, and the Enchant spells turn moonstone and rosestone amulets into pendants.",
  ] },
  { id: 28, date: "2026-09-29", title: "Clearer panel tabs", items: [
    "The side panel's tabs have new icons, drawn crisp and shaded like the items so each is easy to tell apart: crossed swords (combat), rising bars (skills), a sealed scroll (quests), a backpack (inventory), a knight's helm (equipment), praying hands (prayer), a spellbook (magic), two Friends (friends), a cog (settings) and a waving smile (emotes).",
  ] },
  { id: 27, date: "2026-09-29", title: "The sigil stone box, and steadier early levels", items: [
    "The sigil stone box: carry it and the sigil stones you mine go into it (up to 120), and an altar presses every stone inside. Right-click to check, fill or empty it. The Tower Stores and Runa's Sigils sell them.",
    "At the bank, right-click a sigil stone box or inkcoal satchel in your pack to Fill it straight from the bank (or empty it in), or use the Fill button.",
    "The first levels of gathering and making skills (fishing, cooking, woodcutting, mining and the rest) come a little slower, starting at under a third of the XP and catching up by level 10. Combat is unchanged.",
  ] },
  { id: 26, date: "2026-09-29", title: "Real hoods, kinder cooking and a new trailer", items: [
    "Hoods (hunter's, frosthide and leather) are proper hoods now: closed all round, with your face looking out of the front, a cowl point behind, and a short capelet over your shoulders.",
    "Cooking burns less while you learn: about one in five at a food's own level, easing off fast. Minnows stop burning at 12, chicken and beef at 14, perch at 22 and carp at 32.",
    "A new trailer on the website: under a minute of the Realm as it plays today.",
  ] },
  { id: 25, date: "2026-09-29", title: "Ruins, a taller Wizards' Tower and steadier dragging", items: [
    "Ruins across the Realm: crumbling old houses, broken round towers and runs of ancient wall in Whisperwood, the Ashen Hills, the farms' edge, the Pale Dunes, the Murkmire, below Frostpeak, round Glass Lake, by the Mossy Ruins and on the Pale Coast. Mossy in the woods, sun-bleached in the dunes, snow-capped up north.",
    "The Wizards' Tower stands much taller from outside, under an eight-sided spire, and its round walls no longer lose their sides.",
    "Facing you, your Friend holds its weapon and shield in the right hands (the mirror of the back view).",
    "Chimneys rise out of their roofs instead of sinking through them.",
    "Dragging items in your pack or bank no longer stops the game taking clicks in Chrome.",
  ] },
  { id: 24, date: "2026-09-29", title: "Bank tabs, a coal satchel and a Grumblin head", items: [
    "Bank tabs: drag an item onto + to start a tab, onto a tab to file it there, or onto another item to move it. Each tab shows its first item, the ∞ tab shows everything, and deposits go into the tab you're looking at. Right-click an item to move it without dragging.",
    "The inkcoal satchel: worn on your back (or carried), it holds 120 inkcoal, fills itself as you mine, and the furnace (and Forgeheart) take from it. Right-click it to check, fill or empty it. The Old miner at the Ashen mine sells them, or stitch one from 3 leather at Crafting 28.",
    "Grumblins very rarely drop a Grumblin head (the chief a little more often). Wear it. Everyone will know.",
    "The Millpond, south of the windmill: net fishing for minnows and a bait spot for perch and carp, close to town for new Friends.",
    "Cooking burns much less while you're learning: minnows, chicken and beef stop burning at level 18–20.",
    "Spells fly as pixel sprites: fire is a little torch flame, water a teardrop, wind a spinning whirl, earth a tumbling boulder, and curses a knot of smoke with eyes.",
    "Bank booths are proper counters now, with a glass screen, brass bars, a ledger and a stack of coins. Tools and weapons stay outside your helm or hood as you swing them.",
  ] },
  { id: 23, date: "2026-09-29", title: "Forged gear: six new tiers, levels 50 to 90", items: [
    "Six forged metals above rarite: Frostsilver (50), Gloomsteel (60), Wyrmscale (70), Hollowsteel (75), Cindersteel (80) and Ashenheart (90). Each makes a full set: dagger, sword, sabre, helm, shield, cuirass, greaves, an axe and a pickaxe, plus a staff, crossbow limbs, arrowheads and bolts.",
    "They're smelted from what the Realm's strongest creatures drop: frost shards (Frost yetis), gloom shards (gloom hounds), wyrm scales (drakes), Hollow essence (sentinels and the Hollow King), cinder cores (cinder drakes and Old Cinder) and Colossus embers (the Ashen Colossus). Smelting and smithing them takes Smithing 86 to 99.",
    "Every piece glows in its metal's light: an icy plume on frostsilver, violet on gloomsteel, ember orange on ashenheart. Forged staffs are metal from foot to orb.",
    "Finished pieces sometimes drop straight from those creatures, and Frostpeak Outfitters sells frostsilver (and rarite tools) for those with the coin.",
    "New axes and pickaxes cut and mine faster at every tier. Ashwood crossbow stocks (Fletching 84) hold the top crossbows, and the rarite crossbow now needs Ranged 45.",
  ] },
  { id: 22, date: "2026-09-28", title: "Fernwick, crossbows, war bows and Hazel's quiver", items: [
    "Fernwick, a woodcutters' village in the heart of Whisperwood (take the woods road west from the Ashen mine): Hazel's War Bows, the Timber Yard (the best price for logs, and axes), a bank, cottages, a willow pond and archery butts.",
    "Crossbows in six tiers: metal limbs from the anvil (two bars) on a stock carved from logs, fitted together with Crafting. Pewter on a wooden stock, blackiron and ashsteel on oak, moonsilver on willow, glimmer on maple, rarite on yew. Or buy the first few at Fletch & Feather.",
    "Crossbows fire bolts (a dozen unfeathered bolts from a bar, then feathers), shoot slower than bows and hit harder, and they're one-handed, so you can carry a shield.",
    "War bows: a heavier bow for every wood, from two logs. Slower to draw, harder hitting, and a tile more reach. The plain war bow needs Ranged 5, and only Hazel sells them.",
    "New quest, Hazel's Quiver: win her grandmother's quiver back from the Grumblin chief and she'll mend it for you. Worn on your back, it calls four in five arrows and bolts straight back to your pack.",
    "The Thought altar has moved out of Fernwick's street to a quiet glade north-east of the village, beside the road to Wyrmreach.",
  ] },
  { id: 21, date: "2026-09-28", title: "Softer rain, clearer settings", items: [
    "Rain is now a soft, steady wash of sound that swells and fades with the weather, instead of a ticking hiss that sounded like footsteps.",
    "Settings has pixel sliders for music, effects and zoom (with their values shown), and the Graphics choice (Auto, High, Low) is easy to read.",
  ] },
  { id: 20, date: "2026-09-28", title: "Redrawn food, bones and ores", items: [
    "Every fish has its own look: minnows swim in a little school, perch are striped, carp are golden and scaly, char have red bellies, grayling and sailfish raise their tall fins, the inkshark is a shark and the inkcrab is a crab.",
    "Chicken is a drumstick and beef is a steak with a rim of fat. Cooked food is browned with grill marks, and burnt food is a charred lump with a wisp of smoke.",
    "Bones, large bones, ink bones and drake bones each look different, and every ore shows its own metal: dull pewter, rusty blackiron, glossy inkcoal, silver-veined moonsilver, glimmer and rarite crystals, and soft clay.",
  ] },
  { id: 19, date: "2026-09-28", title: "Signs, banners and a log out button", items: [
    "Every shop and bank has a hanging sign outside its door, painted with what's sold inside (an axe for Axel's, a bow for Fletch & Feather, coins for the banks, a horse for the stables).",
    "Banners of your own Rare Friend fly around the fountain square and at the castle gate.",
    "Save and log out: the ⏻ button by the minimap (or Settings) saves your adventure at once and returns to the title screen, confirming it's safe in this browser.",
    "The early levels are a little slower (about half speed at level 1, full speed from level 30), so each level-up means more. Higher levels are unchanged.",
    "Shields show only on the arm they're worn on: across your body facing one way, tucked behind you facing the other.",
    "The inventory squares are a touch smaller, so all 28 fit without scrolling.",
  ] },
  { id: 18, date: "2026-09-28", title: "Animations in your Friend's hands", items: [
    "Weapons and tools now move in your Friend's own pixels instead of floating beside it: swords wind up, strike and follow through, staffs thrust forward as a spell leaves, and bows flex.",
    "Axes chop, pickaxes strike the rock, hammers ring on the anvil, rods cast with the line running from the rod's tip, and food is held out over the fire, all drawn in the same pixel style as your gear.",
    "Other players' Friends animate the same way.",
  ] },
  { id: 17, date: "2026-09-28", title: "Multiplayer that gets through", items: [
    "Players on networks that block direct browser-to-browser links can now see each other: the game falls back to passing messages through public relays, so nobody is stuck at 1 online.",
    "Direct links are still used when they work (faster, and private messages stay off the relays). Hover the online badge to see how you're connected.",
  ] },
  { id: 16, date: "2026-09-28", title: "First steps, graphics settings and the farm", items: [
    "New Friends get a guided start: seven quick steps (a tree, a fire, a fish, cooking, the horses, King Hollis, the Realm Daily) with a gold arrow showing the way, and 500 coins and a Lamp of insight at the end. Skippable any time.",
    "Settings → Graphics: Auto, High or Low. Low draws plain ground and walls, skips ambient life and fog, and runs several times faster on older devices. Auto switches to Low by itself if the game runs slowly.",
    "The stables have moved beside the Rare Market, facing the path, with the paddock next door.",
    "Hollow Farms: the cows have a new pen out by the windmill, the windmill is rebuilt in stone with lattice sails, there's a new chicken coop, and the miller has a farmhouse.",
  ] },
  { id: 15, date: "2026-09-28", title: "World boss, duels, pets and achievements", items: [
    "The Ashen Colossus rises in Wyrmreach every two hours (on the even UTC hours) for twenty minutes. It takes a crowd, and everyone who wounds it shares the loot.",
    "The Sparring Ring, east of Market Street: step inside and right-click another player to Fight. Duels are safe: nobody dies or loses items, and wins are counted.",
    "Six pets to find while you train: Stumpy (woodcutting), Pebble (mining), Bubbles (fishing), Mote (Sigilcraft), Emberling (dragons) and Cinderkin (the Colossus). Call them from the Friends tab.",
    "Achievements: 32 to earn, on a new tab of this popup, and counted on your adventurer card.",
    "Hiscores in the Friends tab: you ranked with every player you've met.",
    "Level-up fireworks that everyone nearby sees. Hoofbeats, dust and a whinny when you ride. Footprints in snow and sand, splashes in the bog. Rare drops shine with a beam of light and a chime.",
    "When a friend near you emotes, your Friend joins in.",
  ] },
  { id: 14, date: "2026-09-28", title: "Daily streaks and this log", items: [
    "Log in every day for a streak reward on a seven-day cycle, up to a Lamp of insight and 5,000 coins on day 7. Each full week adds 25% to the coins.",
    "Three daily challenges, the same for everyone: gain XP in two skills and defeat some monsters. Finish all three to open the daily chest.",
    "This Updates tab: see what's changed after every update. Reopen it any time with the button by the minimap.",
    "Your adventurer card shows your Friend exactly as in the Realm: helm, cape, shield, weapon, and the mount you're riding.",
    "A one-minute trailer at the top of the website.",
  ] },
  { id: 13, date: "2026-09-27", title: "The Friendhollow stables", items: [
    "Marigold's stables, west of the castle, sell eight mounts for RF: six horses and two unicorns. Horses and a unicorn graze in the paddock.",
    "Riding carries you two or three tiles a tick without using run energy, and every mount has a gift: healing, faster gathering, more coins, Defence, XP or light in the dark.",
    "Ride or dismount with the saddle button by the run orb, or H. Other players see you riding, and ridden towards you, your mount's head is in front of you.",
  ] },
  { id: 12, date: "2026-09-27", title: "Gear you can see", items: [
    "Helms, hats, shields and weapons are painted into your Friend's own pixels and move with you: blades in a ready guard, staffs upright with their orb, bows held by the grip, axes on the shoulder.",
    "Weapons swing free only mid-attack.",
  ] },
  { id: 11, date: "2026-09-27", title: "Trading fixes and referral limits", items: [
    "Trades now work when both players ask at the same moment, when a request is answered late, and with the game open in two tabs.",
    "Referral rewards: up to five a day. Any more are credited on a later day you're both online.",
  ] },
  { id: 10, date: "2026-09-27", title: "Shops, ground and fires", items: [
    "General stores in Emberforge, Frostpeak and the Oasis. Every trader buys back what it sells, and what you sell sits on the shelf to buy back.",
    "Grass, paths, cobbled streets and flagstones in the same pixel style as the buildings.",
    "Furnaces are brick kilns with fire in the mouth. Campfires are small pixel flames on cut logs.",
    "The Rare Market's list scrolls.",
  ] },
  { id: 9, date: "2026-09-27", title: "Weather", items: [
    "Rain, and storms with lightning and thunder, from the real clock, so everyone online shares the same sky.",
    "Ground fog at dawn, darker nights, and light that pools on the ground around lamps, torches and fires.",
  ] },
  { id: 8, date: "2026-09-27", title: "Referral codes and the Friendship cape", items: [
    "Share your code (RF- and your Friend #): a new friend who uses it and you both get 250 coins and +15% XP for an hour of play.",
    "Your first referral earns the Friendship cape, with its own emote.",
    "Fires and torches burn in hand-drawn pixel fire.",
  ] },
  { id: 7, date: "2026-09-27", title: "Spells, hats and the night light", items: [
    "Spells are shaped by their element: flame, wave, whirlwind, boulder and curse.",
    "The hat or helm you wear shows on your Friend. Staffs sit lower in the hand, and your night light is dimmer.",
  ] },
  { id: 6, date: "2026-09-27", title: "Fight together, skill guides", items: [
    "Fight the same monster as other players, with shared HP and each other's health bars.",
    "Click a skill for what it unlocks at every level, and browse the recipe book. Guides for every skill are on the website too.",
  ] },
  { id: 5, date: "2026-09-27", title: "Trading, emotes and save codes", items: [
    "Trade items with other players, old-school style, and pick up what they drop.",
    "Fourteen emotes. Magic glows and lights the dark, and dungeons are truly dark.",
    "Save codes (Settings) keep your whole adventure in one line of text.",
  ] },
  { id: 4, date: "2026-09-27", title: "Play together", items: [
    "See everyone else's Friends in the Realm: public chat, whispers, a friends list, follow, and +5% XP near friends.",
  ] },
  { id: 3, date: "2026-09-27", title: "Magic, crafting and dragons", items: [
    "Fletching and Sigilcraft, the Wizards' Tower and its Archmage, and dragons in Wyrmreach.",
    "Right-click in every interface, pixel-art buildings and redrawn items.",
  ] },
  { id: 2, date: "2026-09-27", title: "Ranged, Slayer and the castle", items: [
    "Ranged and Slayer, mastery capes at 99, a bigger Friendhollow with Market Street, and the Rare Market in five towns.",
    "Friendhollow Castle: three storeys, spiral stairs, King Hollis and the battlements. Day and night, and a clearer minimap.",
  ] },
  { id: 1, date: "2026-09-27", title: "The Realm opens", items: [
    "An old-school adventure starring the Rare Friend you own: skills, quests, a 2.5D world and the Hollow King to end.",
  ] },
];
export const LATEST_UPDATE = UPDATES[0].id;
